In [1]:
%pip install -q requests pandas "numpy<2.0" scikit-learn matplotlib gymnasium shimmy tqdm rich "stable-baselines3[extra]"

Note: you may need to restart the kernel to use updated packages.

In [2]:
from __future__ import annotations

import ast
import json
import os
import random
import time
from typing import Any, Dict, List, Optional, Tuple

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
import pandas as pd
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

pd.set_option("display.max_columns", 200)

GAMMA_BASE = "https://gamma-api.polymarket.com"
CLOB_BASE = "https://clob.polymarket.com"

CONFIG = {
    "keyword": None,
    "max_markets": 500,
    "page_limit": 500,
    "active": True,
    "closed": False,
    "min_liquidity": 1000.0,
    "min_volume": 1000.0,
    "interval": "max",
    "fidelity": 60,
    "start_ts": None,
    "end_ts": None,
    "outdir": "polymarket_output_rl_tuned",
    "sleep_sec": 0.1,
}

RL_CONFIG = {
    "lookback": 32,
    "allow_short": False,
    "transaction_cost": 0.0025,
    "initial_cash": 1000.0,
    "action_bins": 5,
    "min_trade_fraction": 0.10,
    "fixed_trade_penalty": 0.0002,
    "risk_aversion": 0.0002,
    "clip_reward": 0.05,
    "timesteps": 5_000_000,
    "learning_rate": 1e-4,
    "n_steps": 4096,
    "batch_size": 512,
    "gamma": 0.995,
    "gae_lambda": 0.98,
    "ent_coef": 0.005,
    "vf_coef": 0.7,
    "clip_range": 0.2,
    "verbose": 1,
    "seed": 42,
    "device": "cuda",
    "train_frac": 0.70,
    "valid_frac": 0.15,
    "num_envs": 8,
    "checkpoint_freq": 100_000,
    "eval_freq": 50_000,
    "policy_hidden_sizes": [256, 256, 128],
}

os.makedirs(CONFIG["outdir"], exist_ok=True)
os.makedirs(os.path.join(CONFIG["outdir"], "per_market"), exist_ok=True)
os.makedirs(os.path.join(CONFIG["outdir"], "checkpoints"), exist_ok=True)
os.makedirs(os.path.join(CONFIG["outdir"], "best_model"), exist_ok=True)

CONFIG, RL_CONFIG

({'keyword': None,
  'max_markets': 500,
  'page_limit': 500,
  'active': True,
  'closed': False,
  'min_liquidity': 1000.0,
  'min_volume': 1000.0,
  'interval': 'max',
  'fidelity': 60,
  'start_ts': None,
  'end_ts': None,
  'outdir': 'polymarket_output_rl_tuned',
  'sleep_sec': 0.1},
 {'lookback': 32,
  'allow_short': False,
  'transaction_cost': 0.0025,
  'initial_cash': 1000.0,
  'action_bins': 5,
  'min_trade_fraction': 0.1,
  'fixed_trade_penalty': 0.0002,
  'risk_aversion': 0.0002,
  'clip_reward': 0.05,
  'timesteps': 5000000,
  'learning_rate': 0.0001,
  'n_steps': 4096,
  'batch_size': 512,
  'gamma': 0.995,
  'gae_lambda': 0.98,
  'ent_coef': 0.005,
  'vf_coef': 0.7,
  'clip_range': 0.2,
  'verbose': 1,
  'seed': 42,
  'device': 'cuda',
  'train_frac': 0.7,
  'valid_frac': 0.15,
  'num_envs': 8,
  'checkpoint_freq': 100000,
  'eval_freq': 50000,
  'policy_hidden_sizes': [256, 256, 128]})

In [3]:
import matplotlib.pyplot as plt
import gymnasium as gym
from gymnasium import spaces

if not hasattr(np, "bool"):
    np.bool = bool

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import CallbackList, CheckpointCallback, EvalCallback
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.vec_env import DummyVecEnv

In [4]:
def make_session() -> requests.Session:
    session = requests.Session()
    retry = Retry(
        total=5,
        read=5,
        connect=5,
        backoff_factor=1.0,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("https://", adapter)
    session.headers.update(
        {
            "User-Agent": "polymarket-dataset-pipeline-notebook/1.0",
            "Accept": "application/json",
        }
    )
    return session

SESSION = make_session()

def parse_maybe_json_array(x: Any) -> List[Any]:
    if x is None:
        return []
    if isinstance(x, list):
        return x
    if isinstance(x, str):
        x = x.strip()
        if not x:
            return []
        try:
            parsed = json.loads(x)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
        try:
            parsed = ast.literal_eval(x)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
    return []

def safe_float(x: Any, default: float = np.nan) -> float:
    try:
        if x is None or x == "":
            return default
        return float(x)
    except Exception:
        return default

def safe_str(x: Any) -> str:
    return "" if x is None else str(x)

def get_json(url: str, params: Optional[Dict[str, Any]] = None) -> Any:
    r = SESSION.get(url, params=params, timeout=60)
    r.raise_for_status()
    return r.json()

In [5]:
def fetch_markets_page(
    limit: int = 100,
    offset: int = 0,
    active: Optional[bool] = True,
    closed: Optional[bool] = False,
    order: str = "volume",
    ascending: bool = False,
) -> List[Dict[str, Any]]:
    params: Dict[str, Any] = {
        "limit": limit,
        "offset": offset,
        "order": order,
        "ascending": str(ascending).lower(),
    }
    if active is not None:
        params["active"] = str(active).lower()
    if closed is not None:
        params["closed"] = str(closed).lower()

    return get_json(f"{GAMMA_BASE}/markets", params=params)

def discover_markets(
    keyword: Optional[str],
    max_markets: int,
    page_limit: int = 100,
    active: Optional[bool] = True,
    closed: Optional[bool] = False,
    min_liquidity: float = 0.0,
    min_volume: float = 0.0,
) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    offset = 0
    keyword_lower = keyword.lower() if keyword else None

    while len(rows) < max_markets:
        page = fetch_markets_page(
            limit=page_limit,
            offset=offset,
            active=active,
            closed=closed,
            order="volume",
            ascending=False,
        )
        if not page:
            break

        for m in page:
            question = safe_str(m.get("question", ""))
            description = safe_str(m.get("description", ""))
            category = safe_str(m.get("category", ""))
            subcategory = safe_str(m.get("subcategory", ""))
            text_blob = " ".join([question, description, category, subcategory]).lower()

            if keyword_lower and keyword_lower not in text_blob:
                continue

            liquidity = safe_float(m.get("liquidity"), 0.0)
            volume = safe_float(m.get("volume"), 0.0)
            if liquidity < min_liquidity or volume < min_volume:
                continue

            clob_token_ids = parse_maybe_json_array(m.get("clobTokenIds"))
            outcomes = parse_maybe_json_array(m.get("outcomes"))
            outcome_prices = parse_maybe_json_array(m.get("outcomePrices"))
            
            if len(clob_token_ids) != 2:
                continue
            
            if len(outcomes) != 2:
                continue

            if not clob_token_ids:
                continue

            yes_token_id = safe_str(clob_token_ids[0]) if len(clob_token_ids) >= 1 else ""
            no_token_id = safe_str(clob_token_ids[1]) if len(clob_token_ids) >= 2 else ""

            row = {
                "market_id": safe_str(m.get("id")),
                "question": question,
                "slug": safe_str(m.get("slug")),
                "category": category,
                "subcategory": subcategory,
                "description": description,
                "liquidity": liquidity,
                "volume": volume,
                "active": m.get("active"),
                "closed": m.get("closed"),
                "archived": m.get("archived"),
                "startDate": safe_str(m.get("startDate")),
                "endDate": safe_str(m.get("endDate")),
                "yes_token_id": yes_token_id,
                "no_token_id": no_token_id,
                "outcomes": json.dumps(outcomes, ensure_ascii=False),
                "outcomePrices": json.dumps(outcome_prices, ensure_ascii=False),
            }
            rows.append(row)

            if len(rows) >= max_markets:
                break

        offset += page_limit

    return pd.DataFrame(rows).drop_duplicates(subset=["market_id"]).reset_index(drop=True)

In [6]:
def fetch_price_history(
    token_id: str,
    interval: str = "1h",
    fidelity: int = 60,
    start_ts: Optional[int] = None,
    end_ts: Optional[int] = None,
) -> pd.DataFrame:
    params: Dict[str, Any] = {
        "market": token_id,
        "interval": interval,
        "fidelity": fidelity,
    }
    if start_ts is not None:
        params["startTs"] = start_ts
    if end_ts is not None:
        params["endTs"] = end_ts

    data = get_json(f"{CLOB_BASE}/prices-history", params=params)

    history = data.get("history", [])
    if not history:
        return pd.DataFrame(columns=["timestamp", "price"])

    df = pd.DataFrame(history)
    if "t" not in df.columns or "p" not in df.columns:
        return pd.DataFrame(columns=["timestamp", "price"])

    df = df.rename(columns={"t": "timestamp", "p": "price"})
    df["timestamp"] = pd.to_datetime(df["timestamp"], unit="s", utc=True)
    df["price"] = pd.to_numeric(df["price"], errors="coerce")
    df = df.dropna(subset=["timestamp", "price"]).sort_values("timestamp").reset_index(drop=True)
    return df

def download_dataset(
    markets_df: pd.DataFrame,
    outdir: str,
    interval: str,
    fidelity: int,
    start_ts: Optional[int],
    end_ts: Optional[int],
    sleep_sec: float = 0.1,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    metadata_path = os.path.join(outdir, "markets.csv")
    prices_path = os.path.join(outdir, "prices.csv")

    all_prices: List[pd.DataFrame] = []
    kept_meta: List[Dict[str, Any]] = []

    for i, row in markets_df.iterrows():
        token_id = row["yes_token_id"]
        if not token_id:
            continue

        try:
            hist = fetch_price_history(
                token_id=token_id,
                interval=interval,
                fidelity=fidelity,
                start_ts=start_ts,
                end_ts=end_ts,
            )
        except Exception as e:
            print(f"[WARN] failed history for market_id={row['market_id']} token={token_id}: {e}")
            continue

        print(f"market_id={row['market_id']} token={token_id} history_rows={len(hist)}")
        if hist.empty or len(hist) < 30:
            print(f"[INFO] skipping market_id={row['market_id']} because history is too short")
            continue

        hist["market_id"] = row["market_id"]
        hist["yes_token_id"] = token_id
        hist["question"] = row["question"]
        hist["category"] = row["category"]
        hist["subcategory"] = row["subcategory"]
        hist["liquidity"] = row["liquidity"]
        hist["volume"] = row["volume"]
        hist["endDate"] = row["endDate"]

        per_market_path = os.path.join(outdir, "per_market", f"{row['market_id']}.csv")
        hist.to_csv(per_market_path, index=False)

        all_prices.append(hist)
        kept_meta.append(row.to_dict())

        print(
            f"[OK] {i + 1}/{len(markets_df)} "
            f"market_id={row['market_id']} rows={len(hist)} "
            f"question={row['question'][:80]}"
        )
        time.sleep(sleep_sec)

    metadata_df = pd.DataFrame(kept_meta).reset_index(drop=True)
    prices_df = pd.concat(all_prices, ignore_index=True) if all_prices else pd.DataFrame()

    metadata_df.to_csv(metadata_path, index=False)
    prices_df.to_csv(prices_path, index=False)

    return metadata_df, prices_df

In [7]:
def add_time_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    ts = pd.to_datetime(df["timestamp"], utc=True)
    df["hour"] = ts.dt.hour
    df["dayofweek"] = ts.dt.dayofweek
    df["dayofmonth"] = ts.dt.day
    return df

def build_features(prices_df: pd.DataFrame) -> pd.DataFrame:
    if prices_df.empty:
        return pd.DataFrame()

    df = prices_df.copy()
    df = df.sort_values(["market_id", "timestamp"]).reset_index(drop=True)
    df["price"] = pd.to_numeric(df["price"], errors="coerce")

    def per_market(g: pd.DataFrame) -> pd.DataFrame:
        g = g.sort_values("timestamp").copy()

        g["ret_1"] = g["price"].pct_change(1)
        g["ret_3"] = g["price"].pct_change(3)
        g["ret_6"] = g["price"].pct_change(6)
        g["ret_12"] = g["price"].pct_change(12)

        g["mom_3"] = g["price"] - g["price"].shift(3)
        g["mom_6"] = g["price"] - g["price"].shift(6)
        g["mom_12"] = g["price"] - g["price"].shift(12)

        g["rolling_mean_6"] = g["price"].rolling(6).mean()
        g["rolling_mean_12"] = g["price"].rolling(12).mean()
        g["rolling_std_6"] = g["price"].rolling(6).std()
        g["rolling_std_12"] = g["price"].rolling(12).std()

        g["zscore_6"] = (g["price"] - g["rolling_mean_6"]) / g["rolling_std_6"]
        g["zscore_12"] = (g["price"] - g["rolling_mean_12"]) / g["rolling_std_12"]

        p = g["price"].clip(1e-5, 1 - 1e-5)
        g["logit_price"] = np.log(p / (1 - p))

        g["future_price"] = g["price"].shift(-1)
        g["future_ret_1"] = g["future_price"] / g["price"] - 1.0
        g["target_up"] = (g["future_ret_1"] > 0).astype(int)

        return g

    feat = df.groupby("market_id", group_keys=False).apply(per_market)
    feat = add_time_features(feat)
    feat = feat.dropna(subset=["future_ret_1", "target_up"]).copy()
    feat = feat.reset_index(drop=True)

    valid_numeric = feat[
        [
            "ret_1",
            "ret_3",
            "ret_6",
            "mom_3",
            "mom_6",
            "rolling_mean_6",
            "rolling_std_6",
            "logit_price",
        ]
    ].notna().sum(axis=1) > 0
    feat = feat.loc[valid_numeric].copy()

    ordered_cols = [
        "timestamp", "question", "yes_token_id", "target_up", "future_ret_1",
        "price", "ret_1", "ret_3", "ret_6", "ret_12",
        "mom_3", "mom_6", "mom_12",
        "rolling_mean_6", "rolling_mean_12",
        "rolling_std_6", "rolling_std_12",
        "zscore_6", "zscore_12", "logit_price",
        "liquidity", "volume", "hour", "dayofweek", "dayofmonth",
        "category", "subcategory", "market_id"
    ]
    ordered_cols = [c for c in ordered_cols if c in feat.columns]
    return feat[ordered_cols].copy()

def time_split(
    feat_df: pd.DataFrame,
    train_frac: float = 0.70,
    valid_frac: float = 0.15,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    df = feat_df.sort_values("timestamp").reset_index(drop=True)
    n = len(df)
    train_end = int(n * train_frac)
    valid_end = int(n * (train_frac + valid_frac))
    train_df = df.iloc[:train_end].copy()
    valid_df = df.iloc[train_end:valid_end].copy()
    test_df = df.iloc[valid_end:].copy()
    return train_df, valid_df, test_df

In [8]:
def fit_baseline_model(
    train_df: pd.DataFrame,
    valid_df: pd.DataFrame,
    test_df: pd.DataFrame,
    outdir: str,
) -> Dict[str, Any]:
    target_col = "target_up"

    train_df = train_df.copy()
    valid_df = valid_df.copy()
    test_df = test_df.copy()

    train_df["question"] = train_df["question"].fillna("")
    valid_df["question"] = valid_df["question"].fillna("")
    test_df["question"] = test_df["question"].fillna("")

    numeric_features = [
        "price",
        "ret_1",
        "ret_3",
        "ret_6",
        "ret_12",
        "mom_3",
        "mom_6",
        "mom_12",
        "rolling_mean_6",
        "rolling_mean_12",
        "rolling_std_6",
        "rolling_std_12",
        "zscore_6",
        "zscore_12",
        "logit_price",
        "liquidity",
        "volume",
        "hour",
        "dayofweek",
        "dayofmonth",
    ]

    categorical_features = ["category", "subcategory", "market_id"]
    text_feature = "question"
    feature_cols = numeric_features + categorical_features + ['question']

    X_train = train_df[feature_cols].copy()
    y_train = train_df[target_col].astype(int).copy()

    X_valid = valid_df[feature_cols].copy()
    y_valid = valid_df[target_col].astype(int).copy()

    X_test = test_df[feature_cols].copy()
    y_test = test_df[target_col].astype(int).copy()

    preprocessor = ColumnTransformer(
        transformers=[
            (
                "num",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="median")),
                        ("scaler", StandardScaler()),
                    ]
                ),
                numeric_features,
            ),
            (
                "cat",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        ("onehot", OneHotEncoder(handle_unknown="ignore")),
                    ]
                ),
                categorical_features,
            ),
            (
                "text",
                TfidfVectorizer(
                    max_features=1000,
                    ngram_range=(1, 2),
                    stop_words="english",
                ),
                "question",
            ),
        ]
    )

    model = LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        solver="liblinear",
        random_state=42,
    )

    pipe = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", model),
        ]
    )

    pipe.fit(X_train, y_train)

    valid_proba = pipe.predict_proba(X_valid)[:, 1]
    valid_pred = (valid_proba >= 0.5).astype(int)

    test_proba = pipe.predict_proba(X_test)[:, 1]
    test_pred = (test_proba >= 0.5).astype(int)

    metrics = {
        "valid_accuracy": float(accuracy_score(y_valid, valid_pred)) if len(y_valid) else np.nan,
        "test_accuracy": float(accuracy_score(y_test, test_pred)) if len(y_test) else np.nan,
        "valid_auc": float(roc_auc_score(y_valid, valid_proba)) if len(np.unique(y_valid)) > 1 else np.nan,
        "test_auc": float(roc_auc_score(y_test, test_proba)) if len(np.unique(y_test)) > 1 else np.nan,
        "n_train": int(len(train_df)),
        "n_valid": int(len(valid_df)),
        "n_test": int(len(test_df)),
        "markets_train": int(train_df["market_id"].nunique()),
        "markets_valid": int(valid_df["market_id"].nunique()),
        "markets_test": int(test_df["market_id"].nunique()),
    }

    with open(os.path.join(outdir, "metrics.json"), "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    with open(os.path.join(outdir, "valid_classification_report.txt"), "w", encoding="utf-8") as f:
        f.write(classification_report(y_valid, valid_pred, digits=4))

    with open(os.path.join(outdir, "test_classification_report.txt"), "w", encoding="utf-8") as f:
        f.write(classification_report(y_test, test_pred, digits=4))

    valid_out = valid_df[["timestamp", "question", "market_id", "target_up", "future_ret_1"]].copy()
    valid_out["pred_proba_up"] = valid_proba
    valid_out["pred_up"] = valid_pred
    valid_out.to_csv(os.path.join(outdir, "valid_predictions.csv"), index=False)

    test_out = test_df[["timestamp", "question", "market_id", "target_up", "future_ret_1"]].copy()
    test_out["pred_proba_up"] = test_proba
    test_out["pred_up"] = test_pred
    test_out.to_csv(os.path.join(outdir, "test_predictions.csv"), index=False)

    return metrics

In [9]:
markets_df = discover_markets(
    keyword=CONFIG["keyword"],
    max_markets=CONFIG["max_markets"],
    page_limit=CONFIG["page_limit"],
    active=CONFIG["active"],
    closed=CONFIG["closed"],
    min_liquidity=CONFIG["min_liquidity"],
    min_volume=CONFIG["min_volume"],
)

markets_df.to_csv(os.path.join(CONFIG["outdir"], "discovered_markets.csv"), index=False)
print(f"Discovered {len(markets_df)} markets")
markets_df.head(10)

Discovered 499 markets

,market_id,question,slug,category,subcategory,description,liquidity,volume,active,closed,archived,startDate,endDate,yes_token_id,no_token_id,outcomes,outcomePrices
0,701726,"Will Hyperliquid reach $100 by December 31, 2026?",will-hyperliquid-reach-100-by-december-31-2026,,,This market will immediately resolve to “Yes” ...,13182.16240,99920.010542,True,False,False,2025-11-24T21:09:54.093719Z,2027-01-01T05:00:00Z,5563253116425987458153208646309676537567512231...,8200389029322785814444369062112915175131090753...,"[""Yes"", ""No""]","[""0.215"", ""0.785""]"
1,1572665,Will Sophia Chikirou advance to the second rou...,will-sophia-chikirou-advance-to-the-second-rou...,,,Municipal elections are scheduled to be held i...,7655.27119,99870.852249,True,False,False,2026-03-13T20:38:32.252617Z,2026-03-15T00:00:00Z,8706457581334293780618009225366654363232945897...,1105570629929405601757662858737525131274474307...,"[""Yes"", ""No""]","[""0.9895"", ""0.0105""]"
2,1602050,VCU Rams vs. North Carolina Tar Heels,cbb-vcu-ncar-2026-03-19,,,"In the upcoming CBB game, scheduled for March ...",81784.00820,9976.279046,True,False,False,2026-03-15T23:03:15.48647Z,2026-03-19T04:00:00Z,8400736124175897848933019720282723570028907889...,6272267179000548293620665438226214625237349562...,"[""VCU Rams"", ""North Carolina Tar Heels""]","[""0.425"", ""0.575""]"
3,1591769,Over $12M committed to the P2P Protocol public...,over-12m-committed-to-the-p2p-protocol-public-...,,,This market will resolve to “Yes” if total com...,2512.26440,9975.973757,True,False,False,2026-03-14T21:34:21.893Z,2026-07-01T04:00:00Z,9225300277532587048629139682480493265214633474...,1885919778921466838271165583781722270087746420...,"[""Yes"", ""No""]","[""0.37"", ""0.63""]"
4,637014,Will Khaled Mashal win the Nobel Peace Prize i...,will-khaled-mashal-win-the-nobel-peace-prize-i...,,,This market will resolve according to the winn...,32336.44221,99751.336413,True,False,False,2025-10-16T22:30:37.055538Z,2026-10-10T00:00:00Z,4817558919700430121831697879056774909752184660...,8718060268156357528336886756762911747500274167...,"[""Yes"", ""No""]","[""0.0045"", ""0.9955""]"
5,1508633,Will FedEx (FDX) beat quarterly earnings?,fdx-quarterly-earnings-nongaap-eps-03-19-2026-...,,,"As of market creation, FedEx is estimated to r...",3518.98580,9974.678856,True,False,False,2026-03-05T17:29:22.655823Z,2026-03-19T21:00:00Z,1042391260369502866632394239175928959586345495...,1083239144752523541872367250761062451264229748...,"[""Yes"", ""No""]","[""0.935"", ""0.065""]"
6,1138909,Masoud Pezeshkian out by December 31?,masoud-pezeshkian-out-by-december-31,,,"This market will resolve to ""Yes"" if the Presi...",11562.17200,99733.677593,True,False,False,2026-01-08T23:55:48.750544Z,2026-12-31T00:00:00Z,2147884814668554283617019600216497883083738090...,6940916877416575789714840524748560996575602373...,"[""Yes"", ""No""]","[""0.425"", ""0.575""]"
7,1469764,Will Ahmad Hosseini Khorasani be head of state...,will-ahmad-hosseini-khorasani-be-head-of-state...,,,This market will resolve to the individual who...,21775.74607,9970.557949,True,False,False,2026-03-01T00:18:26.28Z,2026-12-31T00:00:00Z,3048248432246166029147846179711140980961385763...,1306016185809624321958931969454195157085558985...,"[""Yes"", ""No""]","[""0.009"", ""0.991""]"
8,1623299,Will Elon Musk post 540-559 tweets from March ...,elon-musk-of-tweets-march-20-march-27-540-559,,,This market will resolve according to the numb...,26323.15857,9967.285485,True,False,False,2026-03-17T04:10:38.916062Z,2026-03-27T16:00:00Z,3067743349795700042726308147610119581123650632...,8520270951799751479389134226982506852511134368...,"[""Yes"", ""No""]","[""0.0075"", ""0.9925""]"
9,676791,Deel IPO before 2027?,deel-ipo-before-2027,,,"This market will resolve to ""Yes"" if the liste...",4220.84120,99661.822013,True,False,False,2025-11-12T21:28:43.84235Z,2026-12-31T00:00:00Z,1032528607001344912728239738123994613079723041...,2428720360848145572270826767845808222911115658...,"[""Yes"", ""No""]","[""0.175"", ""0.825""]"

In [10]:
metadata_df, prices_df = download_dataset(
    markets_df=markets_df,
    outdir=CONFIG["outdir"],
    interval=CONFIG["interval"],
    fidelity=CONFIG["fidelity"],
    start_ts=CONFIG["start_ts"],
    end_ts=CONFIG["end_ts"],
    sleep_sec=CONFIG["sleep_sec"],
)

print(f"Kept {len(metadata_df)} markets")
print(f"Downloaded {len(prices_df)} price rows")
prices_df.head()

market_id=701726 token=55632531164259874581532086463096765375675122310464288883906870061905029632548 history_rows=672
[OK] 1/499 market_id=701726 rows=672 question=Will Hyperliquid reach $100 by December 31, 2026?
market_id=1572665 token=87064575813342937806180092253666543632329458979432586376676088759901734231755 history_rows=78
[OK] 2/499 market_id=1572665 rows=78 question=Will Sophia Chikirou advance to the second round of the 2026 Paris municipal ele
market_id=1602050 token=84007361241758978489330197202827235700289078898880514910472901778979242019662 history_rows=42
[OK] 3/499 market_id=1602050 rows=42 question=VCU Rams vs. North Carolina Tar Heels
market_id=1591769 token=92253002775325870486291396824804932652146334743548025985493394591638559052006 history_rows=68
[OK] 4/499 market_id=1591769 rows=68 question=Over $12M committed to the P2P Protocol public sale?
market_id=637014 token=4817558919700430121831697879056774909752184660255737582917693916506064447935 history_rows=652
[OK] 5/499 market_id=637014 rows=652 question=Will Khaled Mashal win the Nobel Peace Prize in 2026?
market_id=1508633 token=104239126036950286663239423917592895958634549572242803554595290903408828749884 history_rows=288
[OK] 6/499 market_id=1508633 rows=288 question=Will FedEx (FDX) beat quarterly earnings?
market_id=1138909 token=21478848146685542836170196002164978830837380902570323687337863795093723563347 history_rows=672
[OK] 7/499 market_id=1138909 rows=672 question=Masoud Pezeshkian out by December 31?
market_id=1469764 token=30482484322461660291478461797111409809613857631053480584753766946651916188092 history_rows=349
[OK] 8/499 market_id=1469764 rows=349 question=Will Ahmad Hosseini Khorasani be head of state in Iran end of 2026?
market_id=1623299 token=30677433497957000427263081476101195811236506320229918438355207407289830567262 history_rows=14
[INFO] skipping market_id=1623299 because history is too short
market_id=676791 token=103252860700134491272823973812399461307972304149985031647360167592025577180003 history_rows=672
[OK] 10/499 market_id=676791 rows=672 question=Deel IPO before 2027?
market_id=679268 token=77089564443108788382233212301997998496655453493992505627581701048596754175114 history_rows=654
[OK] 11/499 market_id=679268 rows=654 question=Will Juliana Stratton be the Democratic nominee for Senate in Illinois?
market_id=1473267 token=71078566425079553968434862040592638030686907991870591875355300263715633063238 history_rows=381
[OK] 12/499 market_id=1473267 rows=381 question=Will BNB dip to $300 in March?
market_id=949493 token=72902726884699850978994485999351956746728455432234001140689757304247177712068 history_rows=655
[OK] 13/499 market_id=949493 rows=655 question=Fed rate cut by March 2026 meeting?
market_id=572841 token=9689498944713823672856130438097273200159148996771826459249142613021421318633 history_rows=669
[OK] 14/499 market_id=572841 rows=669 question=Will Liverpool be relegated from the English Premier League after the 2025–26 se
market_id=1552222 token=51390413670497951732626266105258164146037965853712428956528300554353322364705 history_rows=143
[OK] 15/499 market_id=1552222 rows=143 question=Will the price of Ethereum be above $2,100 on March 17?
market_id=643491 token=24230628024667318915408030183594378763409991714860259271563253789955497902770 history_rows=641
[OK] 16/499 market_id=643491 rows=641 question=Will the Oklahoma City Thunder finish with the best record in the NBA?
market_id=568629 token=107914991083456571784595699074570871171796147416537665179743787749934466771632 history_rows=589
[OK] 17/499 market_id=568629 rows=589 question=Will Scottie Scheffler win the 2026 Masters tournament?
market_id=1007631 token=64873759235836285759433963153564476696368251894659048693711318733282140962729 history_rows=609
[OK] 18/499 market_id=1007631 rows=609 question=Will Russia enter Druzkhivka by June 30?
market_id=898414 token=740554372395562969852824732102908743873362172986366970263111332168756914258 history_rows=636
[OK] 19/499 market_id=898414 rows=636 question=Will Isack Hadjar be the 2026 F1 Drivers' Champion?
market_id=1123274 token=76382316827845441517472068360457192939739928812321416090863010007374866001242 history_rows=669
[OK] 20/499 market_id=1123274 rows=669 question=Will Cristian Sanabria win the 2026 Sucre mayoral election?
market_id=658126 token=85942265466488014050178628789837529099253370994950475616619512156841463704755 history_rows=626
[OK] 21/499 market_id=658126 rows=626 question=Will Argentina dollarize by June 30, 2026?
market_id=561984 token=85795532452312461688342921814235563171225750416821603832877839950165564679042 history_rows=670
[OK] 22/499 market_id=561984 rows=670 question=Will Robert F. Kennedy Jr. win the 2028 Republican presidential nomination?
market_id=1340115 token=8255309310479132845053854355955620107904888669469836543504890654808009858099 history_rows=628
[OK] 23/499 market_id=1340115 rows=628 question=Backpack FDV above $500M one day after launch?
market_id=1262307 token=6086710667492353410204192591618089956254768761665436997493704553708890383193 history_rows=669
[OK] 24/499 market_id=1262307 rows=669 question=Spread: Grizzlies (-3.5)
market_id=1261937 token=67709513442167699686197732054836827267904025831077049202685888929670362112037 history_rows=672
[OK] 25/499 market_id=1261937 rows=672 question=Spread: Grizzlies (-2.5)
market_id=1032414 token=76403301255619580198650998982254456069969388149960661767492909890991734286170 history_rows=660
[OK] 26/499 market_id=1032414 rows=660 question=Will Crude Oil (CL) hit (LOW) $35 by end of June?
market_id=1473204 token=962680704190255252026439494355852805657157139265891326850026080985333953866 history_rows=364
[OK] 27/499 market_id=1473204 rows=364 question=Will Solana dip to $80 in March?
market_id=643914 token=4544017361742200601934350219342651059923509072305426296185227009873229199268 history_rows=665
[OK] 28/499 market_id=643914 rows=665 question=Will Mitchell Robinson lead the NBA in rebounds during the 2025–26 NBA season?
market_id=1460620 token=59956731805320700522586997613751524323693576827770666226633723795095479111207 history_rows=427
[OK] 29/499 market_id=1460620 rows=427 question=Will Apple (AAPL) close above $240 end of March?
market_id=608397 token=53703724894913146397718355589619605161922119509512772920279877071805641165559 history_rows=670
[OK] 30/499 market_id=608397 rows=670 question=Will Stripe not IPO by June 30, 2026?
market_id=1294367 token=6560955416760780987139315342473694721423540017491511872815502412244438128860 history_rows=631
[OK] 31/499 market_id=1294367 rows=631 question=Will Gold (GC) hit (HIGH) $7,000 by end of December?
market_id=1087075 token=54582569831063355530072247029106943322776446137021951658697094382165387213201 history_rows=618
[OK] 32/499 market_id=1087075 rows=618 question=Will any AI model reach a Chatbot Arena score of at least 1600 by December 31?
market_id=824323 token=67753086383762088864161297709367328448408579986910861794977082512790786712560 history_rows=641
[OK] 33/499 market_id=824323 rows=641 question=Will Bruce Blakeman win the 2026 New York Governor Republican primary election?
market_id=1473272 token=102462794083615071900208238312311712725283083634725838536728413703927958585592 history_rows=397
[OK] 34/499 market_id=1473272 rows=397 question=Will Hyperliquid dip to $16 in March?
market_id=1499966 token=30924034022137330553647284706837439008892567483569987506243284967151501025032 history_rows=312
[OK] 35/499 market_id=1499966 rows=312 question=Will James Talarico win the Texas Democratic Senate Primary by between 6.00% and
market_id=801449 token=83519181807223149176944154673874245034190466411042063015447181347367071679109 history_rows=669
[OK] 36/499 market_id=801449 rows=669 question=Will Anthropic have the best AI model at the end of March 2026?
market_id=1473241 token=75768225548184496543490462843501280910650897007401860579693153426016358181445 history_rows=387
[OK] 37/499 market_id=1473241 rows=387 question=Will Hyperliquid reach $48 in March?
market_id=553870 token=66366257655830261525886886009374355528181312179120554384746710233627914852488 history_rows=672
[OK] 38/499 market_id=553870 rows=672 question=Will the Dallas Mavericks win the 2026 NBA Finals?
market_id=568654 token=50485141698460524424531442527506087516895508458870363041201923729224224475501 history_rows=670
[OK] 39/499 market_id=568654 rows=670 question=Will Max Homa win the 2026 Masters tournament?
market_id=1551827 token=57967634168572673905727611135293011597046176141249102107704311772007648906912 history_rows=162
[OK] 40/499 market_id=1551827 rows=162 question=Will "Bridgerton: Season 4" be the top US Netflix show this week?
market_id=1599467 token=86530156700266699861635887822439553785827581179912341289269332113853358966013 history_rows=49
[OK] 41/499 market_id=1599467 rows=49 question=XRP Up or Down - March 17, 1PM ET
market_id=954524 token=86519523855891705470235661348827086848371943654954516794653287557600469512720 history_rows=627
[OK] 42/499 market_id=954524 rows=627 question=Will Resni.ca (Res) win the most seats in the 2026 Slovenian parliamentary elect
market_id=1586085 token=25512798006327178603740980495150234891257173245996130233490218817220447454183 history_rows=80
[OK] 43/499 market_id=1586085 rows=80 question=Will the highest temperature in Shanghai be 8°C on March 18?
market_id=947273 token=9682518067153576122489405729520126083014940106724522567955145436832495666332 history_rows=611
[OK] 44/499 market_id=947273 rows=611 question=Will Alfonso López Chau win the 2026 Peruvian presidential election?
market_id=1500945 token=78940606229390770956621005545960828019783169527776356780468786821621741751930 history_rows=276
[OK] 45/499 market_id=1500945 rows=276 question=Spread: Manchester City FC (-1.5)
market_id=670370 token=2573207755291238620520169357234429566264425244697480836231467818450524491984 history_rows=668
[OK] 46/499 market_id=670370 rows=668 question=OpenAI receives federal backstop for infrastructure before July?
market_id=907351 token=59656689376391478992047627305387889696334448714393302553238770768257543491730 history_rows=660
[OK] 47/499 market_id=907351 rows=660 question=Will Ed Hale win the 2026 Maryland Governor Republican primary election?
market_id=676783 token=44253773982269647786001433323095618605413985786094225082181566233253570490080 history_rows=626
[OK] 48/499 market_id=676783 rows=626 question=Vanta IPO before 2027?
market_id=558952 token=99303605181956827630838461879484468077121754034387765735989859308848389894408 history_rows=637
[OK] 49/499 market_id=558952 rows=637 question=Will Canada win the 2026 FIFA World Cup?
market_id=1046969 token=23504610470727598790580938881988856370252594922846273634046709990914298457008 history_rows=662
[OK] 50/499 market_id=1046969 rows=662 question=Tim Walz charged by December 31, 2026?
market_id=1552231 token=81221731837308949265586387306011650807904625098782438477199407090941265341458 history_rows=169
[OK] 51/499 market_id=1552231 rows=169 question=Will the price of Bitcoin be greater than $80,000 on March 17?
market_id=644024 token=106072602074315884799990195167770552952665946873762031568508532473255399483010 history_rows=672
[OK] 52/499 market_id=644024 rows=672 question=Will Derrick White lead the NBA in three pointers made during the 2025–26 NBA se
market_id=1287618 token=29464984159527182226786284598084151852915087509927059755874912820881004290711 history_rows=666
[OK] 53/499 market_id=1287618 rows=666 question=Abstract FDV above $1B one day after launch?
market_id=1399217 token=25259798694418880321363333200869223748114755185835920437087826647486578921607 history_rows=587
[OK] 54/499 market_id=1399217 rows=587 question=Will Fluminense FC win on 2026-03-18?
market_id=1097730 token=29765742191817129447644931228351252525093921166235658978788622749969406719586 history_rows=647
[OK] 55/499 market_id=1097730 rows=647 question=Maduro guilty of all counts?
market_id=561231 token=8113830512143065501177519557124858581375945005490796772950589720955457782465 history_rows=669
[OK] 56/499 market_id=561231 rows=669 question=Will Alexandria Ocasio-Cortez win the 2028 US Presidential Election?
market_id=947274 token=31366905060250352809933074814832465062746377846325454298457938183906229951978 history_rows=671
[OK] 57/499 market_id=947274 rows=671 question=Will Vladimir Cerrón win the 2026 Peruvian presidential election?
market_id=568631 token=110418008203792792268114717933058884388143135270395587506293975692059241151415 history_rows=658
[OK] 58/499 market_id=568631 rows=658 question=Will Bryson Dechambeau win the 2026 Masters tournament?
market_id=1552206 token=60518059173883223265985432061095193450406420051481058642259038967248285383453 history_rows=169
[OK] 59/499 market_id=1552206 rows=169 question=Will the price of Bitcoin be between $62,000 and $64,000 on March 17?
market_id=1552361 token=82750188706856494395535021885775684160229853419532481637468815247067572390802 history_rows=167
[OK] 60/499 market_id=1552361 rows=167 question=Will the price of XRP be between $1.70 and $1.80 on March 17?
market_id=1610287 token=89393305097656549047050573295225717779622924187690245074644067230907664736604 history_rows=22
[INFO] skipping market_id=1610287 because history is too short
market_id=1492660 token=578603372963860120300833641099476426784317795851277056008416043262589706738 history_rows=299
[OK] 62/499 market_id=1492660 rows=299 question=Will S&P 500 (SPX) hit $7,000 (HIGH) in March 2026?
market_id=1588553 token=46918919453431372096338967709526470428304431876719173200248882507926424321035 history_rows=74
[OK] 63/499 market_id=1588553 rows=74 question=Will Elon Musk post 215-239 tweets from March 16 to March 18, 2026?
market_id=1552971 token=51395300980905119634818010174637602088139397943912279630710509963329641144711 history_rows=160
[OK] 64/499 market_id=1552971 rows=160 question=Will Liverpool reach the UEFA Champions League quarter-finals?
market_id=1611062 token=87981562779362188477390789755302940156563158889336682710721516558324386271580 history_rows=20
[INFO] skipping market_id=1611062 because history is too short
market_id=1500951 token=101386400926285327209638375536839764384935613348790100332426680461908616337631 history_rows=297
[OK] 66/499 market_id=1500951 rows=297 question=Manchester City FC vs. Real Madrid CF: O/U 3.5
market_id=923369 token=35783091872076904029651247098591653806922599943508841638070982679022166075193 history_rows=659
[OK] 67/499 market_id=923369 rows=659 question=Will Chaikasem Nitisiri be the next prime minister of Thailand?
market_id=1086972 token=41245949300586088132481639672255490865734578503276380308361324401464866738140 history_rows=670
[OK] 68/499 market_id=1086972 rows=670 question=VEO 4 released by March 31, 2026?
market_id=1500590 token=104382982037765182209957785782217933217555132793954125254149193900733072796577 history_rows=300
[OK] 69/499 market_id=1500590 rows=300 question=Hamad bin Isa Al Khalifa out as leader of Bahrain?
market_id=675610 token=112301341215896295950926815860953912723192228131080168008844064431674732802852 history_rows=663
[OK] 70/499 market_id=675610 rows=663 question=Will Waymo operate in 11 cities on June 30 2026?
market_id=1367023 token=45192403302189095705690124053194394317106648523509681372554623453292460725314 history_rows=672
[OK] 71/499 market_id=1367023 rows=672 question=Will Clavicular be named People's Sexiest Man Alive in 2026?
market_id=763535 token=50657735872283319690883578987928100255120760107016028333366029287044304026888 history_rows=672
[OK] 72/499 market_id=763535 rows=672 question=Backpack FDV above $700M one day after launch?
market_id=1561022 token=111541632589117380942144256416103192645033735405889739976395652041511128190975 history_rows=140
[OK] 73/499 market_id=1561022 rows=140 question=No token launch by March 31
market_id=1366979 token=86937291847794294690913688156961279382256085186875614088885940188286408701268 history_rows=659
[OK] 74/499 market_id=1366979 rows=659 question=Will Heart for The Hague (HvDH) win the most seats in The Hague’s 2026 municipal
market_id=1432294 token=19288143399774859830944664729623949193919584402723401862679475500023591936981 history_rows=468
[OK] 75/499 market_id=1432294 rows=468 question=Will Google reach $320 in March?
market_id=1544795 token=99390970186095476158604553843389938788064583141526825109668507201084266675707 history_rows=161
[OK] 76/499 market_id=1544795 rows=161 question=Alexandre de Moraes out as Brazil Supreme Court Justice?
market_id=678749 token=2016831347927446419180834317602987894480801436994223278564280138881400953952 history_rows=669
[OK] 77/499 market_id=678749 rows=669 question=Will Israel strike 6 countries in 2026?
market_id=665218 token=86727316187077924188803504745015598973723867072517640274231186919208073176698 history_rows=671
[OK] 78/499 market_id=665218 rows=671 question=Israel and Saudi Arabia normalize relations before 2027?
market_id=1588571 token=1464834072892203603529279579314126103010025649443071803546204915030432731934 history_rows=74
[OK] 79/499 market_id=1588571 rows=74 question=Will the price of Ethereum be above $2,400 on March 21?
market_id=1280793 token=84357600230025345245988905658786788578454211224023948178259553114344917506444 history_rows=636
[OK] 80/499 market_id=1280793 rows=636 question=Will the Democratic Party win the AL-01 House seat?
market_id=629065 token=14106559958736396166532779557992677195131704671903638051108803362785186765280 history_rows=669
[OK] 81/499 market_id=629065 rows=669 question=Will the Minnesota Wild win the Central Division?
market_id=665503 token=67565972075898091709163371829761231762318232475740950317083391526954889294846 history_rows=669
[OK] 82/499 market_id=665503 rows=669 question=Cap on gambling loss deductions repealed by March 31?
market_id=1448079 token=96028212841194754459555089575409089943633909939641459170176129652418386270449 history_rows=417
[OK] 83/499 market_id=1448079 rows=417 question=Will Seattle have between 6 and 7 inches of precipitation in March?
market_id=950069 token=87110780312285474621239667044237697542604250455560114346256685967576937445146 history_rows=611
[OK] 84/499 market_id=950069 rows=611 question=Will the Fed decide differently in the next three decisions (Jan–Mar–Apr)?
market_id=631045 token=47848555635748009983462962481545341194026880518141560747711492227563791266566 history_rows=672
[OK] 85/499 market_id=631045 rows=672 question=Will the Republicans win the Florida Senate race in 2026?
market_id=1339769 token=32100646597103151520708930825184762124585961199171649862922931416837210460836 history_rows=672
[OK] 86/499 market_id=1339769 rows=672 question=Will Bitcoin dip to $30,000 by December 31, 2026?
market_id=599354 token=56458125489755148756983070575884285785306433056136202728957154557809707541174 history_rows=595
[OK] 87/499 market_id=599354 rows=595 question=Will Lindsey Graham be the Republican nominee for Senate in South Carolina?
market_id=631129 token=103370314319568567853309723519846779114498839892746332550236915054534902010310 history_rows=672
[OK] 88/499 market_id=631129 rows=672 question=Will Meituan have the top AI model at the end of June 2026?
market_id=1397303 token=36998557109668706896790710976403990069251870375760916003616734609949340893230 history_rows=628
[OK] 89/499 market_id=1397303 rows=628 question=Will Russia capture all of Stepnohirsk by April 30, 2026?
market_id=665245 token=57853859046646923423953764718940196552745906795417540913347938528167751330524 history_rows=669
[OK] 90/499 market_id=665245 rows=669 question=Yoon out of custody by March 31?
market_id=665502 token=82192875338543444321050059158489019675098254652958667767854340749139444164787 history_rows=641
[OK] 91/499 market_id=665502 rows=641 question=Will a province schedule a referendum to leave Canada before 2027?
market_id=643497 token=88119791447611473328638942674181360035865487773273698951216278909819893594583 history_rows=642

,timestamp,price,market_id,yes_token_id,question,category,subcategory,liquidity,volume,endDate
0,2026-02-17 18:00:35+00:00,0.180,701726,5563253116425987458153208646309676537567512231...,"Will Hyperliquid reach $100 by December 31, 2026?",,,13182.1624,99920.010542,2027-01-01T05:00:00Z
1,2026-02-17 19:00:32+00:00,0.180,701726,5563253116425987458153208646309676537567512231...,"Will Hyperliquid reach $100 by December 31, 2026?",,,13182.1624,99920.010542,2027-01-01T05:00:00Z
2,2026-02-17 20:00:17+00:00,0.185,701726,5563253116425987458153208646309676537567512231...,"Will Hyperliquid reach $100 by December 31, 2026?",,,13182.1624,99920.010542,2027-01-01T05:00:00Z
3,2026-02-17 21:00:23+00:00,0.185,701726,5563253116425987458153208646309676537567512231...,"Will Hyperliquid reach $100 by December 31, 2026?",,,13182.1624,99920.010542,2027-01-01T05:00:00Z
4,2026-02-17 22:00:19+00:00,0.185,701726,5563253116425987458153208646309676537567512231...,"Will Hyperliquid reach $100 by December 31, 2026?",,,13182.1624,99920.010542,2027-01-01T05:00:00Z

In [11]:
print("Unique markets:", prices_df["market_id"].nunique())
print("Min timestamp:", prices_df["timestamp"].min())
print("Max timestamp:", prices_df["timestamp"].max())
print("Rows per market summary:")
prices_df.groupby("market_id").size().describe()

Unique markets: 472
Min timestamp: 2026-02-17 18:00:26+00:00
Max timestamp: 2026-03-17 17:59:35+00:00
Rows per market summary:

count    472.000000
mean     516.631356
std      217.057145
min       33.000000
25%      363.000000
50%      641.000000
75%      669.000000
max      672.000000
dtype: float64

In [12]:
metadata_df[["market_id", "question", "category", "liquidity", "volume", "endDate"]].head(20)

,market_id,question,category,liquidity,volume,endDate
0,701726,"Will Hyperliquid reach $100 by December 31, 2026?",,13182.16240,99920.010542,2027-01-01T05:00:00Z
1,1572665,Will Sophia Chikirou advance to the second rou...,,7655.27119,99870.852249,2026-03-15T00:00:00Z
2,1602050,VCU Rams vs. North Carolina Tar Heels,,81784.00820,9976.279046,2026-03-19T04:00:00Z
3,1591769,Over $12M committed to the P2P Protocol public...,,2512.26440,9975.973757,2026-07-01T04:00:00Z
4,637014,Will Khaled Mashal win the Nobel Peace Prize i...,,32336.44221,99751.336413,2026-10-10T00:00:00Z
5,1508633,Will FedEx (FDX) beat quarterly earnings?,,3518.98580,9974.678856,2026-03-19T21:00:00Z
6,1138909,Masoud Pezeshkian out by December 31?,,11562.17200,99733.677593,2026-12-31T00:00:00Z
7,1469764,Will Ahmad Hosseini Khorasani be head of state...,,21775.74607,9970.557949,2026-12-31T00:00:00Z
8,676791,Deel IPO before 2027?,,4220.84120,99661.822013,2026-12-31T00:00:00Z
9,679268,Will Juliana Stratton be the Democratic nomine...,,13007.79760,99570.468947,2026-03-17T00:00:00Z
10,1473267,Will BNB dip to $300 in March?,,13947.10969,9953.610809,2026-04-01T04:00:00Z
11,949493,Fed rate cut by March 2026 meeting?,,38711.61369,994543.068958,2026-03-18T00:00:00Z
12,572841,Will Liverpool be relegated from the English P...,,23500.51263,99433.425564,2026-05-27T00:00:00Z
13,1552222,"Will the price of Ethereum be above $2,100 on ...",,186061.98980,99362.970115,2026-03-17T16:00:00Z
14,643491,Will the Oklahoma City Thunder finish with the...,,4930.71190,99199.953403,
15,568629,Will Scottie Scheffler win the 2026 Masters to...,,111514.28870,99040.191846,2026-04-13T00:00:00Z
16,1007631,Will Russia enter Druzkhivka by June 30?,,10836.35460,99036.601627,2026-06-30T00:00:00Z
17,898414,Will Isack Hadjar be the 2026 F1 Drivers' Cham...,,205683.24789,989946.027123,2026-12-06T00:00:00Z
18,1123274,Will Cristian Sanabria win the 2026 Sucre mayo...,,5409.23660,9898.776242,2026-03-22T00:00:00Z
19,658126,"Will Argentina dollarize by June 30, 2026?",,4686.12799,9892.624233,2026-06-30T00:00:00Z

In [13]:
feat_df = build_features(prices_df)
feat_df.to_csv(os.path.join(CONFIG["outdir"], "features.csv"), index=False)

print("Feature rows:", len(feat_df))
feat_df.head()

Feature rows: 243378

,timestamp,question,yes_token_id,target_up,future_ret_1,price,ret_1,ret_3,ret_6,ret_12,mom_3,mom_6,mom_12,rolling_mean_6,rolling_mean_12,rolling_std_6,rolling_std_12,zscore_6,zscore_12,logit_price,liquidity,volume,hour,dayofweek,dayofmonth,category,subcategory,market_id
0,2026-02-17 18:00:32+00:00,Will the Bharatiya Janata Party (BJP) win the ...,1011427917241379403799484981250977225770917971...,0,0.0,0.0035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.651486,5959.80386,8610.168405,18,1,17,,,1003791
1,2026-02-17 19:00:31+00:00,Will the Bharatiya Janata Party (BJP) win the ...,1011427917241379403799484981250977225770917971...,0,0.0,0.0035,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.651486,5959.80386,8610.168405,19,1,17,,,1003791
2,2026-02-17 20:00:16+00:00,Will the Bharatiya Janata Party (BJP) win the ...,1011427917241379403799484981250977225770917971...,0,0.0,0.0035,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.651486,5959.80386,8610.168405,20,1,17,,,1003791
3,2026-02-17 21:00:21+00:00,Will the Bharatiya Janata Party (BJP) win the ...,1011427917241379403799484981250977225770917971...,0,0.0,0.0035,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.651486,5959.80386,8610.168405,21,1,17,,,1003791
4,2026-02-17 22:00:17+00:00,Will the Bharatiya Janata Party (BJP) win the ...,1011427917241379403799484981250977225770917971...,0,0.0,0.0035,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.651486,5959.80386,8610.168405,22,1,17,,,1003791

In [14]:
def build_rl_features(prices_df: pd.DataFrame, lookback: int = 20) -> pd.DataFrame:
    df = prices_df.copy()
    df = df.sort_values(["market_id", "timestamp"]).reset_index(drop=True)
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    df["price"] = pd.to_numeric(df["price"], errors="coerce")
    df["liquidity"] = pd.to_numeric(df["liquidity"], errors="coerce").fillna(0.0)
    df["volume"] = pd.to_numeric(df["volume"], errors="coerce").fillna(0.0)
    df["endDate_dt"] = pd.to_datetime(df["endDate"], errors="coerce", utc=True)

    def per_market(g: pd.DataFrame) -> pd.DataFrame:
        g = g.sort_values("timestamp").copy()
        g["ret_1"] = g["price"].pct_change(1).fillna(0.0)
        g["ret_2"] = g["price"].pct_change(2).fillna(0.0)
        g["ret_3"] = g["price"].pct_change(3).fillna(0.0)
        g["ret_6"] = g["price"].pct_change(6).fillna(0.0)
        g["ret_12"] = g["price"].pct_change(12).fillna(0.0)

        g["mom_3"] = (g["price"] - g["price"].shift(3)).fillna(0.0)
        g["mom_6"] = (g["price"] - g["price"].shift(6)).fillna(0.0)

        g["rolling_mean_6"] = g["price"].rolling(6).mean()
        g["rolling_mean_12"] = g["price"].rolling(12).mean()
        g["rolling_std_6"] = g["price"].rolling(6).std()
        g["rolling_std_12"] = g["price"].rolling(12).std()

        g["rolling_mean_6"] = g["rolling_mean_6"].fillna(method="bfill").fillna(g["price"])
        g["rolling_mean_12"] = g["rolling_mean_12"].fillna(method="bfill").fillna(g["price"])
        g["rolling_std_6"] = g["rolling_std_6"].fillna(method="bfill").fillna(0.0)
        g["rolling_std_12"] = g["rolling_std_12"].fillna(method="bfill").fillna(0.0)

        g["zscore_6"] = ((g["price"] - g["rolling_mean_6"]) / (g["rolling_std_6"] + 1e-8)).fillna(0.0)
        g["zscore_12"] = ((g["price"] - g["rolling_mean_12"]) / (g["rolling_std_12"] + 1e-8)).fillna(0.0)

        p = g["price"].clip(1e-5, 1 - 1e-5)
        g["logit_price"] = np.log(p / (1 - p))

        if g["endDate_dt"].notna().any():
            g["time_to_expiry_hours"] = ((g["endDate_dt"] - g["timestamp"]).dt.total_seconds() / 3600.0).clip(lower=0.0)
        else:
            g["time_to_expiry_hours"] = 0.0

        g["next_price"] = g["price"].shift(-1)
        g["next_ret"] = (g["next_price"] / g["price"] - 1.0).replace([np.inf, -np.inf], 0.0).fillna(0.0)

        g["market_age_steps"] = np.arange(len(g))
        g["market_length"] = len(g)

        return g

    feat = df.groupby("market_id", group_keys=False).apply(per_market).reset_index(drop=True)

    keep_cols = [
        "timestamp", "market_id", "question", "category", "subcategory",
        "price", "next_price", "next_ret", "ret_1", "ret_2", "ret_3", "ret_6", "ret_12",
        "mom_3", "mom_6", "rolling_mean_6", "rolling_mean_12",
        "rolling_std_6", "rolling_std_12", "zscore_6", "zscore_12",
        "logit_price", "liquidity", "volume", "time_to_expiry_hours",
        "market_age_steps", "market_length"
    ]
    feat = feat[keep_cols].copy()

    numeric_cols = [
        "price", "next_price", "next_ret", "ret_1", "ret_2", "ret_3", "ret_6", "ret_12",
        "mom_3", "mom_6", "rolling_mean_6", "rolling_mean_12",
        "rolling_std_6", "rolling_std_12", "zscore_6", "zscore_12",
        "logit_price", "liquidity", "volume", "time_to_expiry_hours",
        "market_age_steps", "market_length"
    ]
    feat[numeric_cols] = feat[numeric_cols].replace([np.inf, -np.inf], 0.0).fillna(0.0)

    feat["question"] = feat["question"].fillna("").astype(str)
    feat["category"] = feat["category"].fillna("unknown").astype(str)
    feat["subcategory"] = feat["subcategory"].fillna("unknown").astype(str)

    counts = feat.groupby("market_id").size()
    valid_ids = counts[counts >= max(lookback + 5, 30)].index
    feat = feat[feat["market_id"].isin(valid_ids)].copy()

    return feat.reset_index(drop=True)

def split_market_history(
    market_df: pd.DataFrame,
    train_frac: float = 0.70,
    valid_frac: float = 0.15,
    lookback: int = 20,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    g = market_df.sort_values("timestamp").reset_index(drop=True)
    n = len(g)
    train_end = int(n * train_frac)
    valid_end = int(n * (train_frac + valid_frac))

    train_df = g.iloc[:train_end].copy()
    valid_df = g.iloc[max(0, train_end - lookback):valid_end].copy()
    test_df = g.iloc[max(0, valid_end - lookback):].copy()
    return train_df, valid_df, test_df


def build_market_splits(
    rl_df: pd.DataFrame,
    train_frac: float,
    valid_frac: float,
    lookback: int,
) -> Tuple[Dict[str, pd.DataFrame], Dict[str, pd.DataFrame], Dict[str, pd.DataFrame]]:
    train_markets: Dict[str, pd.DataFrame] = {}
    valid_markets: Dict[str, pd.DataFrame] = {}
    test_markets: Dict[str, pd.DataFrame] = {}

    for market_id, g in rl_df.groupby("market_id"):
        train_df, valid_df, test_df = split_market_history(
            g, train_frac=train_frac, valid_frac=valid_frac, lookback=lookback
        )
        if len(train_df) >= lookback + 5:
            train_markets[market_id] = train_df.reset_index(drop=True)
        if len(valid_df) >= lookback + 5:
            valid_markets[market_id] = valid_df.reset_index(drop=True)
        if len(test_df) >= lookback + 5:
            test_markets[market_id] = test_df.reset_index(drop=True)

    return train_markets, valid_markets, test_markets


rl_df = build_rl_features(prices_df, lookback=RL_CONFIG["lookback"])
train_markets, valid_markets, test_markets = build_market_splits(
    rl_df,
    train_frac=RL_CONFIG["train_frac"],
    valid_frac=RL_CONFIG["valid_frac"],
    lookback=RL_CONFIG["lookback"],
)

print("RL rows:", len(rl_df))
print("Train markets:", len(train_markets))
print("Valid markets:", len(valid_markets))
print("Test markets:", len(test_markets))

rl_df.head()

RL rows: 243817
Train markets: 459
Valid markets: 461
Test markets: 471

,timestamp,market_id,question,category,subcategory,price,next_price,next_ret,ret_1,ret_2,ret_3,ret_6,ret_12,mom_3,mom_6,rolling_mean_6,rolling_mean_12,rolling_std_6,rolling_std_12,zscore_6,zscore_12,logit_price,liquidity,volume,time_to_expiry_hours,market_age_steps,market_length
0,2026-02-17 18:00:32+00:00,1003791,Will the Bharatiya Janata Party (BJP) win the ...,,,0.0035,0.0035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0035,0.0035,0.0,0.0,0.0,0.0,-5.651486,5959.80386,8610.168405,1949.991111,0,670
1,2026-02-17 19:00:31+00:00,1003791,Will the Bharatiya Janata Party (BJP) win the ...,,,0.0035,0.0035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0035,0.0035,0.0,0.0,0.0,0.0,-5.651486,5959.80386,8610.168405,1948.991389,1,670
2,2026-02-17 20:00:16+00:00,1003791,Will the Bharatiya Janata Party (BJP) win the ...,,,0.0035,0.0035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0035,0.0035,0.0,0.0,0.0,0.0,-5.651486,5959.80386,8610.168405,1947.995556,2,670
3,2026-02-17 21:00:21+00:00,1003791,Will the Bharatiya Janata Party (BJP) win the ...,,,0.0035,0.0035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0035,0.0035,0.0,0.0,0.0,0.0,-5.651486,5959.80386,8610.168405,1946.994167,3,670
4,2026-02-17 22:00:17+00:00,1003791,Will the Bharatiya Janata Party (BJP) win the ...,,,0.0035,0.0035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0035,0.0035,0.0,0.0,0.0,0.0,-5.651486,5959.80386,8610.168405,1945.995278,4,670

In [15]:
class PolymarketTradingEnv(gym.Env):
    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        markets: Dict[str, pd.DataFrame],
        lookback: int = 20,
        transaction_cost: float = 0.002,
        risk_aversion: float = 0.0005,
        clip_reward: float = 0.2,
        allow_short: bool = False,
        initial_cash: float = 1000.0,
        action_bins: int = 11,
        min_trade_fraction: float = 0.0,
        fixed_trade_penalty: float = 0.0,
        deterministic_market_order: bool = False,
        seed: int = 42,
    ):
        super().__init__()

        self.markets = {
            str(k): v.sort_values("timestamp").reset_index(drop=True).copy()
            for k, v in markets.items()
            if len(v) >= lookback + 5
        }

        self.market_ids = list(self.markets.keys())
        self.lookback = lookback
        self.transaction_cost = transaction_cost
        self.risk_aversion = risk_aversion
        self.clip_reward = clip_reward
        self.allow_short = allow_short
        self.initial_cash = float(initial_cash)
        self.action_bins = int(action_bins)
        self.min_trade_fraction = float(min_trade_fraction)
        self.fixed_trade_penalty = float(fixed_trade_penalty)
        self.deterministic_market_order = deterministic_market_order
        self.seed_value = seed

        self.rng = np.random.default_rng(seed)
        self.market_cursor = 0

        self.extra_feature_names = [
            "price",
            "no_price",
            "logit_price",
            "ret_1",
            "ret_3",
            "ret_6",
            "rolling_std_6",
            "zscore_6",
            "time_to_expiry_hours",
            "liquidity",
            "volume",
            "cash_frac",
            "yes_frac",
            "no_frac",
            "cash_to_initial",
            "yes_qty",
            "no_qty",
            "nav_to_initial",
        ]
        obs_dim = self.lookback + len(self.extra_feature_names)

        self.action_space = spaces.MultiDiscrete([5, self.action_bins])
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(obs_dim,),
            dtype=np.float32,
        )

        self.current_market_id: Optional[str] = None
        self.current_df: Optional[pd.DataFrame] = None
        self.current_step = self.lookback
        self.cash = self.initial_cash
        self.yes_qty = 0.0
        self.no_qty = 0.0
        self.equity = self.initial_cash
        self.done = False

    def _select_market_id(self) -> str:
        if self.deterministic_market_order:
            market_id = self.market_ids[self.market_cursor % len(self.market_ids)]
            self.market_cursor += 1
            return market_id
        return str(self.rng.choice(self.market_ids))

    def _current_prices(self) -> Tuple[float, float]:
        assert self.current_df is not None
        row = self.current_df.iloc[self.current_step]
        yes_price = float(np.clip(row["price"], 1e-6, 1.0 - 1e-6))
        no_price = float(np.clip(1.0 - yes_price, 1e-6, 1.0 - 1e-6))
        return yes_price, no_price

    def _portfolio_value(self, yes_price: float, no_price: float) -> float:
        return float(self.cash + self.yes_qty * yes_price + self.no_qty * no_price)

    def _get_obs(self) -> np.ndarray:
        assert self.current_df is not None
        start = self.current_step - self.lookback
        end = self.current_step
        window = self.current_df.iloc[start:end]

        returns_window = window["ret_1"].to_numpy(dtype=np.float32)
        if len(returns_window) < self.lookback:
            pad = np.zeros(self.lookback - len(returns_window), dtype=np.float32)
            returns_window = np.concatenate([pad, returns_window])

        row = self.current_df.iloc[self.current_step]
        yes_price, no_price = self._current_prices()
        nav = self._portfolio_value(yes_price, no_price)
        nav_denom = max(nav, 1e-8)

        cash_frac = self.cash / nav_denom
        yes_frac = (self.yes_qty * yes_price) / nav_denom
        no_frac = (self.no_qty * no_price) / nav_denom

        extras = np.array([
            float(yes_price),
            float(no_price),
            float(row["logit_price"]),
            float(row["ret_1"]),
            float(row["ret_3"]),
            float(row["ret_6"]),
            float(row["rolling_std_6"]),
            float(row["zscore_6"]),
            float(row["time_to_expiry_hours"]) / 24.0,
            np.log1p(float(row["liquidity"])),
            np.log1p(float(row["volume"])),
            float(cash_frac),
            float(yes_frac),
            float(no_frac),
            float(self.cash / max(self.initial_cash, 1e-8)),
            float(self.yes_qty),
            float(self.no_qty),
            float(nav / max(self.initial_cash, 1e-8)),
        ], dtype=np.float32)

        obs = np.concatenate([returns_window, extras]).astype(np.float32)
        obs = np.nan_to_num(obs, nan=0.0, posinf=0.0, neginf=0.0)
        return obs

    def reset(self, *, seed: Optional[int] = None, options: Optional[dict] = None):
        super().reset(seed=seed)
        if seed is not None:
            self.rng = np.random.default_rng(seed)

        self.current_market_id = self._select_market_id()
        self.current_df = self.markets[self.current_market_id]
        self.current_step = self.lookback
        self.cash = self.initial_cash
        self.yes_qty = 0.0
        self.no_qty = 0.0
        yes_price, no_price = self._current_prices()
        self.equity = self._portfolio_value(yes_price, no_price)
        self.done = False

        obs = self._get_obs()
        info = {
            "market_id": self.current_market_id,
            "timestamp": self.current_df.iloc[self.current_step]["timestamp"],
        }
        return obs, info

    def step(self, action):
        assert self.current_df is not None

        action_arr = np.asarray(action).reshape(-1)
        action_type = int(action_arr[0])
        size_bin = int(action_arr[1]) if len(action_arr) > 1 else 0
        max_bin = max(self.action_bins - 1, 1)
        size_fraction = float(np.clip(size_bin / max_bin, 0.0, 1.0))

        if size_fraction < self.min_trade_fraction:
            action_type = 0
            size_fraction = 0.0

        yes_price, no_price = self._current_prices()
        nav_before = self._portfolio_value(yes_price, no_price)

        trade_notional = 0.0
        fees_paid = 0.0
        executed_qty = 0.0
        forced_liquidation_notional = 0.0
        forced_liquidation_fees = 0.0

        if action_type == 1:
            if self.no_qty > 0.0:
                gross_proceeds = self.no_qty * no_price
                liq_fee = gross_proceeds * self.transaction_cost
                self.cash += max(gross_proceeds - liq_fee, 0.0)
                forced_liquidation_notional += gross_proceeds
                forced_liquidation_fees += liq_fee
                self.no_qty = 0.0

            spend = size_fraction * self.cash
            if spend > 0.0:
                fees_paid = spend * self.transaction_cost
                effective_spend = max(spend - fees_paid, 0.0)
                executed_qty = effective_spend / max(yes_price, 1e-8)
                self.cash -= spend
                self.yes_qty += executed_qty
                trade_notional = spend

        elif action_type == 2:
            if self.yes_qty > 0.0:
                gross_proceeds = self.yes_qty * yes_price
                liq_fee = gross_proceeds * self.transaction_cost
                self.cash += max(gross_proceeds - liq_fee, 0.0)
                forced_liquidation_notional += gross_proceeds
                forced_liquidation_fees += liq_fee
                self.yes_qty = 0.0

            spend = size_fraction * self.cash
            if spend > 0.0:
                fees_paid = spend * self.transaction_cost
                effective_spend = max(spend - fees_paid, 0.0)
                executed_qty = effective_spend / max(no_price, 1e-8)
                self.cash -= spend
                self.no_qty += executed_qty
                trade_notional = spend

        elif action_type == 3:
            qty = size_fraction * self.yes_qty
            if qty > 0.0:
                gross_proceeds = qty * yes_price
                fees_paid = gross_proceeds * self.transaction_cost
                self.cash += max(gross_proceeds - fees_paid, 0.0)
                self.yes_qty -= qty
                executed_qty = qty
                trade_notional = gross_proceeds

        elif action_type == 4:
            qty = size_fraction * self.no_qty
            if qty > 0.0:
                gross_proceeds = qty * no_price
                fees_paid = gross_proceeds * self.transaction_cost
                self.cash += max(gross_proceeds - fees_paid, 0.0)
                self.no_qty -= qty
                executed_qty = qty
                trade_notional = gross_proceeds

        fees_paid += forced_liquidation_fees
        trade_notional += forced_liquidation_notional

        self.current_step += 1
        if self.current_step >= len(self.current_df) - 1:
            self.done = True

        yes_price_next, no_price_next = self._current_prices()
        nav_after = self._portfolio_value(yes_price_next, no_price_next)
        pnl = nav_after - nav_before
        reward = pnl / max(nav_before, 1e-8)

        if self.risk_aversion > 0.0:
            exposure_value = self.yes_qty * yes_price_next + self.no_qty * no_price_next
            leverage_like = exposure_value / max(nav_after, 1e-8)
            risk_penalty = self.risk_aversion * leverage_like
            reward -= risk_penalty
        else:
            risk_penalty = 0.0

        trade_penalty = self.fixed_trade_penalty if trade_notional > 0.0 else 0.0
        reward -= trade_penalty

        if self.clip_reward is not None:
            reward = float(np.clip(reward, -self.clip_reward, self.clip_reward))

        self.equity = nav_after

        obs = self._get_obs()
        info = {
            "market_id": self.current_market_id,
            "timestamp": self.current_df.iloc[self.current_step]["timestamp"],
            "price": yes_price_next,
            "no_price": no_price_next,
            "next_ret": float(self.current_df.iloc[self.current_step]["next_ret"]),
            "category": str(self.current_df.iloc[self.current_step].get("category", "")),
            "action_type": action_type,
            "size_bin": size_bin,
            "size_fraction": size_fraction,
            "cash": float(self.cash),
            "yes_qty": float(self.yes_qty),
            "no_qty": float(self.no_qty),
            "trade_notional": float(trade_notional),
            "fees_paid": float(fees_paid),
            "executed_qty": float(executed_qty),
            "forced_liquidation_notional": float(forced_liquidation_notional),
            "portfolio_value": float(nav_after),
            "reward": float(reward),
            "risk_penalty": float(risk_penalty),
            "trade_penalty": float(trade_penalty),
        }
        return obs, float(reward), self.done, False, info

In [16]:

def make_train_env(rank: int = 0):
    def _init() -> PolymarketTradingEnv:
        return PolymarketTradingEnv(
            markets=train_markets,
            lookback=RL_CONFIG["lookback"],
            transaction_cost=RL_CONFIG["transaction_cost"],
            risk_aversion=RL_CONFIG["risk_aversion"],
            clip_reward=RL_CONFIG["clip_reward"],
            allow_short=RL_CONFIG["allow_short"],
            deterministic_market_order=False,
            initial_cash=RL_CONFIG["initial_cash"],
            action_bins=RL_CONFIG["action_bins"],
            min_trade_fraction=RL_CONFIG["min_trade_fraction"],
            fixed_trade_penalty=RL_CONFIG["fixed_trade_penalty"],
            seed=RL_CONFIG["seed"] + rank,
        )
    return _init


def make_eval_env(markets_dict: Dict[str, pd.DataFrame]) -> PolymarketTradingEnv:
    return PolymarketTradingEnv(
        markets=markets_dict,
        lookback=RL_CONFIG["lookback"],
        transaction_cost=RL_CONFIG["transaction_cost"],
        risk_aversion=RL_CONFIG["risk_aversion"],
        clip_reward=RL_CONFIG["clip_reward"],
        allow_short=RL_CONFIG["allow_short"],
        deterministic_market_order=True,
        initial_cash=RL_CONFIG["initial_cash"],
        action_bins=RL_CONFIG["action_bins"],
        min_trade_fraction=RL_CONFIG["min_trade_fraction"],
        fixed_trade_penalty=RL_CONFIG["fixed_trade_penalty"],
        seed=RL_CONFIG["seed"],
    )


vec_train_env = DummyVecEnv([make_train_env(rank=i) for i in range(RL_CONFIG["num_envs"])])
vec_valid_env = DummyVecEnv([lambda: make_eval_env(valid_markets)])
print(f"Training env ready with {RL_CONFIG['num_envs']} parallel episodes.")

Training env ready with 8 parallel episodes.

In [17]:
policy_kwargs = dict(
    net_arch=dict(
        pi=RL_CONFIG["policy_hidden_sizes"],
        vf=RL_CONFIG["policy_hidden_sizes"],
    )
)

checkpoint_callback = CheckpointCallback(
    save_freq=max(RL_CONFIG["checkpoint_freq"] // RL_CONFIG["num_envs"], 1),
    save_path=os.path.join(CONFIG["outdir"], "checkpoints"),
    name_prefix="ppo_polymarket",
)

eval_callback = EvalCallback(
    vec_valid_env,
    best_model_save_path=os.path.join(CONFIG["outdir"], "best_model"),
    log_path=os.path.join(CONFIG["outdir"], "eval_logs"),
    eval_freq=max(RL_CONFIG["eval_freq"] // RL_CONFIG["num_envs"], 1),
    deterministic=True,
    render=False,
)

callback = CallbackList([checkpoint_callback, eval_callback])

ppo_model = PPO(
    policy="MlpPolicy",
    env=vec_train_env,
    learning_rate=RL_CONFIG["learning_rate"],
    n_steps=RL_CONFIG["n_steps"],
    batch_size=RL_CONFIG["batch_size"],
    gamma=RL_CONFIG["gamma"],
    gae_lambda=RL_CONFIG["gae_lambda"],
    ent_coef=RL_CONFIG["ent_coef"],
    vf_coef=RL_CONFIG["vf_coef"],
    clip_range=RL_CONFIG["clip_range"],
    verbose=RL_CONFIG["verbose"],
    seed=RL_CONFIG["seed"],
    tensorboard_log=os.path.join(CONFIG["outdir"], "tensorboard"),
    device=RL_CONFIG["device"],
    policy_kwargs=policy_kwargs,
)

ppo_model.learn(
    total_timesteps=RL_CONFIG["timesteps"],
    progress_bar=True,
    callback=callback,
)

final_model_path = os.path.join(CONFIG["outdir"], "ppo_polymarket_trader")
ppo_model.save(final_model_path)
print(f"Saved final PPO model to {final_model_path}")

best_model_path = os.path.join(CONFIG["outdir"], "best_model", "best_model.zip")
if os.path.exists(best_model_path):
    best_model = PPO.load(best_model_path, device=RL_CONFIG["device"])
    print(f"Loaded best validation model from {best_model_path}")
else:
    best_model = ppo_model

Using cuda device
Logging to polymarket_output_rl_tuned/tensorboard/PPO_7

Output()

/home/kevinshi/jupyterlab/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:283: UserWarning:
    Found GPU0 NVIDIA GB10 which is of cuda capability 12.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (8.0) - (12.0)

  warnings.warn(
/home/kevinshi/jupyterlab/.venv/lib/python3.12/site-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(

------------------------------
| time/              |       |
|    fps             | 3731  |
|    iterations      | 1     |
|    time_elapsed    | 8     |
|    total_timesteps | 32768 |
------------------------------

/home/kevinshi/jupyterlab/.venv/lib/python3.12/site-packages/stable_baselines3/common/evaluation.py:70:
UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting
modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first
with ``Monitor`` wrapper.
  warnings.warn(

Eval num_timesteps=50000, episode_reward=0.00 +/- 0.00

Episode length: 97.60 +/- 3.83

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 50000       |
| train/                  |             |
|    approx_kl            | 0.009528933 |
|    clip_fraction        | 0.0665      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.21       |
|    explained_variance   | -9.25       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0105     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00525    |
|    value_loss           | 0.0104      |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 3254  |
|    iterations      | 2     |
|    time_elapsed    | 20    |
|    total_timesteps | 65536 |
------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3175        |
|    iterations           | 3           |
|    time_elapsed         | 30          |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.009436121 |
|    clip_fraction        | 0.0695      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.2        |
|    explained_variance   | -0.215      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0209     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00461    |
|    value_loss           | 0.00423     |
-----------------------------------------

Eval num_timesteps=100000, episode_reward=0.00 +/- 0.00

Episode length: 99.20 +/- 0.75

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 100000      |
| train/                  |             |
|    approx_kl            | 0.007620476 |
|    clip_fraction        | 0.0453      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.17       |
|    explained_variance   | 0.121       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0211     |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.00359    |
|    value_loss           | 0.00435     |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3130   |
|    iterations      | 4      |
|    time_elapsed    | 41     |
|    total_timesteps | 131072 |
-------------------------------

Eval num_timesteps=150000, episode_reward=0.00 +/- 0.00

Episode length: 95.80 +/- 4.45

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 95.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 150000       |
| train/                  |              |
|    approx_kl            | 0.0071697277 |
|    clip_fraction        | 0.0686       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.13        |
|    explained_variance   | -0.0334      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0225      |
|    n_updates            | 40           |
|    policy_gradient_loss | -0.00431     |
|    value_loss           | 0.00315      |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3094   |
|    iterations      | 5      |
|    time_elapsed    | 52     |
|    total_timesteps | 163840 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3086        |
|    iterations           | 6           |
|    time_elapsed         | 63          |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.007823309 |
|    clip_fraction        | 0.0686      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.1        |
|    explained_variance   | -0.0257     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0235     |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.00483    |
|    value_loss           | 0.00245     |
-----------------------------------------

Eval num_timesteps=200000, episode_reward=0.00 +/- 0.00

Episode length: 97.00 +/- 4.05

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 200000      |
| train/                  |             |
|    approx_kl            | 0.006296874 |
|    clip_fraction        | 0.0491      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.08       |
|    explained_variance   | -0.0927     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0261     |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.00422    |
|    value_loss           | 0.00228     |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3072   |
|    iterations      | 7      |
|    time_elapsed    | 74     |
|    total_timesteps | 229376 |
-------------------------------

Eval num_timesteps=250000, episode_reward=0.00 +/- 0.00

Episode length: 97.80 +/- 2.99

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 250000       |
| train/                  |              |
|    approx_kl            | 0.0075237723 |
|    clip_fraction        | 0.0495       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.05        |
|    explained_variance   | -0.0211      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0258      |
|    n_updates            | 70           |
|    policy_gradient_loss | -0.00499     |
|    value_loss           | 0.00189      |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3059   |
|    iterations      | 8      |
|    time_elapsed    | 85     |
|    total_timesteps | 262144 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3069        |
|    iterations           | 9           |
|    time_elapsed         | 96          |
|    total_timesteps      | 294912      |
| train/                  |             |
|    approx_kl            | 0.007498999 |
|    clip_fraction        | 0.06        |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.03       |
|    explained_variance   | -0.0399     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0164     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.00602    |
|    value_loss           | 0.00191     |
-----------------------------------------

Eval num_timesteps=300000, episode_reward=0.00 +/- 0.00

Episode length: 98.80 +/- 0.75

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 300000      |
| train/                  |             |
|    approx_kl            | 0.006291966 |
|    clip_fraction        | 0.0511      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3          |
|    explained_variance   | -0.00924    |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0215     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.00492    |
|    value_loss           | 0.00196     |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3063   |
|    iterations      | 10     |
|    time_elapsed    | 106    |
|    total_timesteps | 327680 |
-------------------------------

Eval num_timesteps=350000, episode_reward=0.00 +/- 0.00

Episode length: 98.20 +/- 2.71

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 350000      |
| train/                  |             |
|    approx_kl            | 0.006706401 |
|    clip_fraction        | 0.0485      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.95       |
|    explained_variance   | -0.0516     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0165     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.00464    |
|    value_loss           | 0.00161     |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3046   |
|    iterations      | 11     |
|    time_elapsed    | 118    |
|    total_timesteps | 360448 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3048        |
|    iterations           | 12          |
|    time_elapsed         | 128         |
|    total_timesteps      | 393216      |
| train/                  |             |
|    approx_kl            | 0.006186417 |
|    clip_fraction        | 0.0504      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.94       |
|    explained_variance   | -0.0111     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0168     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00488    |
|    value_loss           | 0.00147     |
-----------------------------------------

Eval num_timesteps=400000, episode_reward=0.00 +/- 0.00

Episode length: 96.20 +/- 2.14

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 400000       |
| train/                  |              |
|    approx_kl            | 0.0067024976 |
|    clip_fraction        | 0.0538       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.92        |
|    explained_variance   | -0.0378      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0139      |
|    n_updates            | 120          |
|    policy_gradient_loss | -0.00471     |
|    value_loss           | 0.00162      |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3044   |
|    iterations      | 13     |
|    time_elapsed    | 139    |
|    total_timesteps | 425984 |
-------------------------------

Eval num_timesteps=450000, episode_reward=-0.00 +/- 0.01

Episode length: 96.40 +/- 3.72

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 96.4        |
|    mean_reward          | -0.00267    |
| time/                   |             |
|    total_timesteps      | 450000      |
| train/                  |             |
|    approx_kl            | 0.007535477 |
|    clip_fraction        | 0.0562      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.9        |
|    explained_variance   | -0.0718     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0232     |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.00526    |
|    value_loss           | 0.00121     |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3034   |
|    iterations      | 14     |
|    time_elapsed    | 151    |
|    total_timesteps | 458752 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3041        |
|    iterations           | 15          |
|    time_elapsed         | 161         |
|    total_timesteps      | 491520      |
| train/                  |             |
|    approx_kl            | 0.007296037 |
|    clip_fraction        | 0.0628      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.86       |
|    explained_variance   | -0.0546     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0159     |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.00527    |
|    value_loss           | 0.000999    |
-----------------------------------------

Eval num_timesteps=500000, episode_reward=0.00 +/- 0.00

Episode length: 99.40 +/- 0.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 500000      |
| train/                  |             |
|    approx_kl            | 0.007954139 |
|    clip_fraction        | 0.0706      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.81       |
|    explained_variance   | -0.00648    |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0172     |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.00634    |
|    value_loss           | 0.00107     |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3039   |
|    iterations      | 16     |
|    time_elapsed    | 172    |
|    total_timesteps | 524288 |
-------------------------------

Eval num_timesteps=550000, episode_reward=0.00 +/- 0.00

Episode length: 97.40 +/- 2.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 550000      |
| train/                  |             |
|    approx_kl            | 0.006366642 |
|    clip_fraction        | 0.0497      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.8        |
|    explained_variance   | -0.052      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0267     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.00512    |
|    value_loss           | 0.000894    |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3032   |
|    iterations      | 17     |
|    time_elapsed    | 183    |
|    total_timesteps | 557056 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3038        |
|    iterations           | 18          |
|    time_elapsed         | 194         |
|    total_timesteps      | 589824      |
| train/                  |             |
|    approx_kl            | 0.005971422 |
|    clip_fraction        | 0.0551      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.76       |
|    explained_variance   | 0.014       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.02       |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00444    |
|    value_loss           | 0.000746    |
-----------------------------------------

Eval num_timesteps=600000, episode_reward=0.00 +/- 0.00

Episode length: 95.80 +/- 3.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 95.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 600000       |
| train/                  |              |
|    approx_kl            | 0.0070713176 |
|    clip_fraction        | 0.0547       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.74        |
|    explained_variance   | 0.069        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0185      |
|    n_updates            | 180          |
|    policy_gradient_loss | -0.00478     |
|    value_loss           | 0.000789     |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3038   |
|    iterations      | 19     |
|    time_elapsed    | 204    |
|    total_timesteps | 622592 |
-------------------------------

Eval num_timesteps=650000, episode_reward=0.00 +/- 0.00

Episode length: 97.20 +/- 2.48

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 650000      |
| train/                  |             |
|    approx_kl            | 0.004725481 |
|    clip_fraction        | 0.0382      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.73       |
|    explained_variance   | -0.023      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0128     |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00376    |
|    value_loss           | 0.000672    |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3038   |
|    iterations      | 20     |
|    time_elapsed    | 215    |
|    total_timesteps | 655360 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3035        |
|    iterations           | 21          |
|    time_elapsed         | 226         |
|    total_timesteps      | 688128      |
| train/                  |             |
|    approx_kl            | 0.005766242 |
|    clip_fraction        | 0.0536      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.69       |
|    explained_variance   | 0.1         |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0221     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00554    |
|    value_loss           | 0.000433    |
-----------------------------------------

Eval num_timesteps=700000, episode_reward=0.00 +/- 0.00

Episode length: 95.20 +/- 3.97

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 95.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 700000      |
| train/                  |             |
|    approx_kl            | 0.004999146 |
|    clip_fraction        | 0.0414      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.66       |
|    explained_variance   | 0.0682      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.011      |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.004      |
|    value_loss           | 0.000477    |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3035   |
|    iterations      | 22     |
|    time_elapsed    | 237    |
|    total_timesteps | 720896 |
-------------------------------

Eval num_timesteps=750000, episode_reward=0.00 +/- 0.00

Episode length: 96.80 +/- 3.66

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 750000       |
| train/                  |              |
|    approx_kl            | 0.0068294727 |
|    clip_fraction        | 0.0545       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.191        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0194      |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.0054      |
|    value_loss           | 0.000472     |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3035   |
|    iterations      | 23     |
|    time_elapsed    | 248    |
|    total_timesteps | 753664 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3039        |
|    iterations           | 24          |
|    time_elapsed         | 258         |
|    total_timesteps      | 786432      |
| train/                  |             |
|    approx_kl            | 0.006046297 |
|    clip_fraction        | 0.056       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.283       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0202     |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00457    |
|    value_loss           | 0.000337    |
-----------------------------------------

Eval num_timesteps=800000, episode_reward=0.00 +/- 0.00

Episode length: 99.60 +/- 0.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 800000      |
| train/                  |             |
|    approx_kl            | 0.006086556 |
|    clip_fraction        | 0.0453      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.334       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0153     |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0043     |
|    value_loss           | 0.000285    |
-----------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3038   |
|    iterations      | 25     |
|    time_elapsed    | 269    |
|    total_timesteps | 819200 |
-------------------------------

Eval num_timesteps=850000, episode_reward=0.00 +/- 0.00

Episode length: 93.60 +/- 5.54

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 93.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 850000       |
| train/                  |              |
|    approx_kl            | 0.0066614253 |
|    clip_fraction        | 0.0482       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | 0.202        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0111      |
|    n_updates            | 250          |
|    policy_gradient_loss | -0.00449     |
|    value_loss           | 0.000201     |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3031   |
|    iterations      | 26     |
|    time_elapsed    | 281    |
|    total_timesteps | 851968 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3032        |
|    iterations           | 27          |
|    time_elapsed         | 291         |
|    total_timesteps      | 884736      |
| train/                  |             |
|    approx_kl            | 0.006509215 |
|    clip_fraction        | 0.0464      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.0785      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0223     |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.00537    |
|    value_loss           | 0.00023     |
-----------------------------------------

Eval num_timesteps=900000, episode_reward=0.00 +/- 0.00

Episode length: 88.80 +/- 3.06

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 88.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 900000       |
| train/                  |              |
|    approx_kl            | 0.0104018925 |
|    clip_fraction        | 0.0646       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.172        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0216      |
|    n_updates            | 270          |
|    policy_gradient_loss | -0.00526     |
|    value_loss           | 0.000228     |
------------------------------------------
-------------------------------
| time/              |        |
|    fps             | 3033   |
|    iterations      | 28     |
|    time_elapsed    | 302    |
|    total_timesteps | 917504 |
-------------------------------

Eval num_timesteps=950000, episode_reward=0.01 +/- 0.02

Episode length: 75.80 +/- 0.98

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 75.8         |
|    mean_reward          | 0.00987      |
| time/                   |              |
|    total_timesteps      | 950000       |
| train/                  |              |
|    approx_kl            | 0.0052875374 |
|    clip_fraction        | 0.0316       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.233        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0122      |
|    n_updates            | 280          |
|    policy_gradient_loss | -0.00597     |
|    value_loss           | 0.000179     |
------------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 3032   |
|    iterations      | 29     |
|    time_elapsed    | 313    |
|    total_timesteps | 950272 |
-------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3033        |
|    iterations           | 30          |
|    time_elapsed         | 324         |
|    total_timesteps      | 983040      |
| train/                  |             |
|    approx_kl            | 0.008377248 |
|    clip_fraction        | 0.0517      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | 0.0246      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0122     |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.00594    |
|    value_loss           | 0.00013     |
-----------------------------------------

Eval num_timesteps=1000000, episode_reward=0.00 +/- 0.00

Episode length: 67.80 +/- 4.53

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 67.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1000000      |
| train/                  |              |
|    approx_kl            | 0.0076216087 |
|    clip_fraction        | 0.0442       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | 0.0221       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0195      |
|    n_updates            | 300          |
|    policy_gradient_loss | -0.00597     |
|    value_loss           | 0.000117     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 3025    |
|    iterations      | 31      |
|    time_elapsed    | 335     |
|    total_timesteps | 1015808 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3025        |
|    iterations           | 32          |
|    time_elapsed         | 346         |
|    total_timesteps      | 1048576     |
| train/                  |             |
|    approx_kl            | 0.006575819 |
|    clip_fraction        | 0.0445      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.58       |
|    explained_variance   | 0.0471      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0171     |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.00621    |
|    value_loss           | 9.94e-05    |
-----------------------------------------

Eval num_timesteps=1050000, episode_reward=0.00 +/- 0.00

Episode length: 63.60 +/- 2.06

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 63.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1050000      |
| train/                  |              |
|    approx_kl            | 0.0067233145 |
|    clip_fraction        | 0.0448       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.259        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0217      |
|    n_updates            | 320          |
|    policy_gradient_loss | -0.0053      |
|    value_loss           | 7.68e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 3028    |
|    iterations      | 33      |
|    time_elapsed    | 357     |
|    total_timesteps | 1081344 |
--------------------------------

Eval num_timesteps=1100000, episode_reward=0.00 +/- 0.00

Episode length: 56.80 +/- 2.71

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 56.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1100000     |
| train/                  |             |
|    approx_kl            | 0.007925981 |
|    clip_fraction        | 0.069       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.11        |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0158     |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.00663    |
|    value_loss           | 9.22e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 3027    |
|    iterations      | 34      |
|    time_elapsed    | 367     |
|    total_timesteps | 1114112 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 3028        |
|    iterations           | 35          |
|    time_elapsed         | 378         |
|    total_timesteps      | 1146880     |
| train/                  |             |
|    approx_kl            | 0.004500885 |
|    clip_fraction        | 0.0318      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | 0.13        |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0142     |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.0038     |
|    value_loss           | 0.000136    |
-----------------------------------------

Eval num_timesteps=1150000, episode_reward=0.00 +/- 0.00

Episode length: 55.20 +/- 1.47

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 55.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1150000     |
| train/                  |             |
|    approx_kl            | 0.008270392 |
|    clip_fraction        | 0.0695      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | 0.276       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0241     |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.00531    |
|    value_loss           | 0.0001      |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 3027    |
|    iterations      | 36      |
|    time_elapsed    | 389     |
|    total_timesteps | 1179648 |
--------------------------------

Eval num_timesteps=1200000, episode_reward=0.00 +/- 0.00

Episode length: 56.20 +/- 2.79

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 56.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1200000     |
| train/                  |             |
|    approx_kl            | 0.007803614 |
|    clip_fraction        | 0.0522      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | -0.0133     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0129     |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.00716    |
|    value_loss           | 7.08e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 3002    |
|    iterations      | 37      |
|    time_elapsed    | 403     |
|    total_timesteps | 1212416 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2991        |
|    iterations           | 38          |
|    time_elapsed         | 416         |
|    total_timesteps      | 1245184     |
| train/                  |             |
|    approx_kl            | 0.006644007 |
|    clip_fraction        | 0.0346      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.379       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0115     |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.00465    |
|    value_loss           | 0.000105    |
-----------------------------------------

Eval num_timesteps=1250000, episode_reward=0.00 +/- 0.00

Episode length: 51.40 +/- 0.80

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 51.4         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1250000      |
| train/                  |              |
|    approx_kl            | 0.0076789553 |
|    clip_fraction        | 0.0682       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | 0.295        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0299      |
|    n_updates            | 380          |
|    policy_gradient_loss | -0.00625     |
|    value_loss           | 2.34e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2980    |
|    iterations      | 39      |
|    time_elapsed    | 428     |
|    total_timesteps | 1277952 |
--------------------------------

Eval num_timesteps=1300000, episode_reward=0.00 +/- 0.00

Episode length: 47.60 +/- 2.73

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 47.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1300000     |
| train/                  |             |
|    approx_kl            | 0.005162184 |
|    clip_fraction        | 0.0352      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | -0.0829     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0181     |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.00643    |
|    value_loss           | 3.87e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2962    |
|    iterations      | 40      |
|    time_elapsed    | 442     |
|    total_timesteps | 1310720 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2952         |
|    iterations           | 41           |
|    time_elapsed         | 455          |
|    total_timesteps      | 1343488      |
| train/                  |              |
|    approx_kl            | 0.0052828477 |
|    clip_fraction        | 0.0396       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -0.215       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0222      |
|    n_updates            | 400          |
|    policy_gradient_loss | -0.0054      |
|    value_loss           | 4.17e-05     |
------------------------------------------

Eval num_timesteps=1350000, episode_reward=0.00 +/- 0.00

Episode length: 43.00 +/- 2.19

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 43           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1350000      |
| train/                  |              |
|    approx_kl            | 0.0072077406 |
|    clip_fraction        | 0.0516       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | 0.461        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0218      |
|    n_updates            | 410          |
|    policy_gradient_loss | -0.0054      |
|    value_loss           | 2.52e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2942    |
|    iterations      | 42      |
|    time_elapsed    | 467     |
|    total_timesteps | 1376256 |
--------------------------------

Eval num_timesteps=1400000, episode_reward=0.00 +/- 0.00

Episode length: 37.00 +/- 6.03

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 37          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1400000     |
| train/                  |             |
|    approx_kl            | 0.008772472 |
|    clip_fraction        | 0.0495      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.349       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0284     |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.00569    |
|    value_loss           | 2.16e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2935    |
|    iterations      | 43      |
|    time_elapsed    | 479     |
|    total_timesteps | 1409024 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2923         |
|    iterations           | 44           |
|    time_elapsed         | 493          |
|    total_timesteps      | 1441792      |
| train/                  |              |
|    approx_kl            | 0.0066807657 |
|    clip_fraction        | 0.0452       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | 0.0446       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0136      |
|    n_updates            | 430          |
|    policy_gradient_loss | -0.0073      |
|    value_loss           | 2.75e-05     |
------------------------------------------

Eval num_timesteps=1450000, episode_reward=0.00 +/- 0.00

Episode length: 28.00 +/- 3.69

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 28          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1450000     |
| train/                  |             |
|    approx_kl            | 0.005072277 |
|    clip_fraction        | 0.0351      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | -0.143      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0315     |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.00541    |
|    value_loss           | 7.14e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2915    |
|    iterations      | 45      |
|    time_elapsed    | 505     |
|    total_timesteps | 1474560 |
--------------------------------

Eval num_timesteps=1500000, episode_reward=0.00 +/- 0.00

Episode length: 25.20 +/- 1.47

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 25.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1500000      |
| train/                  |              |
|    approx_kl            | 0.0067185583 |
|    clip_fraction        | 0.0551       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.158        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0284      |
|    n_updates            | 450          |
|    policy_gradient_loss | -0.005       |
|    value_loss           | 8e-06        |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2908    |
|    iterations      | 46      |
|    time_elapsed    | 518     |
|    total_timesteps | 1507328 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2893         |
|    iterations           | 47           |
|    time_elapsed         | 532          |
|    total_timesteps      | 1540096      |
| train/                  |              |
|    approx_kl            | 0.0075015672 |
|    clip_fraction        | 0.0667       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -0.117       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.012       |
|    n_updates            | 460          |
|    policy_gradient_loss | -0.00584     |
|    value_loss           | 4.06e-05     |
------------------------------------------

Eval num_timesteps=1550000, episode_reward=0.00 +/- 0.00

Episode length: 21.40 +/- 2.58

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 21.4         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1550000      |
| train/                  |              |
|    approx_kl            | 0.0064031207 |
|    clip_fraction        | 0.0401       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -0.209       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0163      |
|    n_updates            | 470          |
|    policy_gradient_loss | -0.00465     |
|    value_loss           | 1.7e-05      |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2887    |
|    iterations      | 48      |
|    time_elapsed    | 544     |
|    total_timesteps | 1572864 |
--------------------------------

Eval num_timesteps=1600000, episode_reward=-0.01 +/- 0.01

Episode length: 20.80 +/- 4.17

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 20.8        |
|    mean_reward          | -0.00702    |
| time/                   |             |
|    total_timesteps      | 1600000     |
| train/                  |             |
|    approx_kl            | 0.005467388 |
|    clip_fraction        | 0.037       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | -0.593      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0261     |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.00701    |
|    value_loss           | 9.24e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2880    |
|    iterations      | 49      |
|    time_elapsed    | 557     |
|    total_timesteps | 1605632 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2873         |
|    iterations           | 50           |
|    time_elapsed         | 570          |
|    total_timesteps      | 1638400      |
| train/                  |              |
|    approx_kl            | 0.0045019984 |
|    clip_fraction        | 0.0251       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -2.97        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0261      |
|    n_updates            | 490          |
|    policy_gradient_loss | -0.00617     |
|    value_loss           | 1.23e-05     |
------------------------------------------

Eval num_timesteps=1650000, episode_reward=0.00 +/- 0.00

Episode length: 22.80 +/- 2.04

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 22.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1650000     |
| train/                  |             |
|    approx_kl            | 0.010201119 |
|    clip_fraction        | 0.0871      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | -0.151      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0177     |
|    n_updates            | 500         |
|    policy_gradient_loss | -0.00683    |
|    value_loss           | 1.96e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2860    |
|    iterations      | 51      |
|    time_elapsed    | 584     |
|    total_timesteps | 1671168 |
--------------------------------

Eval num_timesteps=1700000, episode_reward=0.00 +/- 0.00

Episode length: 23.60 +/- 0.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 23.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1700000     |
| train/                  |             |
|    approx_kl            | 0.006776496 |
|    clip_fraction        | 0.0598      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | -0.368      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0207     |
|    n_updates            | 510         |
|    policy_gradient_loss | -0.00554    |
|    value_loss           | 2.11e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2855    |
|    iterations      | 52      |
|    time_elapsed    | 596     |
|    total_timesteps | 1703936 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2850        |
|    iterations           | 53          |
|    time_elapsed         | 609         |
|    total_timesteps      | 1736704     |
| train/                  |             |
|    approx_kl            | 0.008286718 |
|    clip_fraction        | 0.0636      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.217       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0148     |
|    n_updates            | 520         |
|    policy_gradient_loss | -0.00718    |
|    value_loss           | 1.81e-05    |
-----------------------------------------

Eval num_timesteps=1750000, episode_reward=0.00 +/- 0.00

Episode length: 20.60 +/- 0.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 20.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1750000      |
| train/                  |              |
|    approx_kl            | 0.0072962632 |
|    clip_fraction        | 0.0367       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.622       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0291      |
|    n_updates            | 530          |
|    policy_gradient_loss | -0.00524     |
|    value_loss           | 2.82e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2845    |
|    iterations      | 54      |
|    time_elapsed    | 621     |
|    total_timesteps | 1769472 |
--------------------------------

Eval num_timesteps=1800000, episode_reward=0.00 +/- 0.00

Episode length: 19.20 +/- 1.47

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 19.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1800000     |
| train/                  |             |
|    approx_kl            | 0.005610933 |
|    clip_fraction        | 0.0391      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.908      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0269     |
|    n_updates            | 540         |
|    policy_gradient_loss | -0.00553    |
|    value_loss           | 4.27e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2837    |
|    iterations      | 55      |
|    time_elapsed    | 635     |
|    total_timesteps | 1802240 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2833         |
|    iterations           | 56           |
|    time_elapsed         | 647          |
|    total_timesteps      | 1835008      |
| train/                  |              |
|    approx_kl            | 0.0067728404 |
|    clip_fraction        | 0.0503       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | -1.16        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0279      |
|    n_updates            | 550          |
|    policy_gradient_loss | -0.00626     |
|    value_loss           | 3.39e-06     |
------------------------------------------

Eval num_timesteps=1850000, episode_reward=0.00 +/- 0.00

Episode length: 14.80 +/- 1.60

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 14.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 1850000      |
| train/                  |              |
|    approx_kl            | 0.0059139365 |
|    clip_fraction        | 0.043        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.6         |
|    explained_variance   | -0.804       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0238      |
|    n_updates            | 560          |
|    policy_gradient_loss | -0.00767     |
|    value_loss           | 6.11e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2829    |
|    iterations      | 57      |
|    time_elapsed    | 660     |
|    total_timesteps | 1867776 |
--------------------------------

Eval num_timesteps=1900000, episode_reward=0.00 +/- 0.00

Episode length: 12.80 +/- 0.98

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 12.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1900000     |
| train/                  |             |
|    approx_kl            | 0.005400247 |
|    clip_fraction        | 0.0461      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | -0.605      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0184     |
|    n_updates            | 570         |
|    policy_gradient_loss | -0.00654    |
|    value_loss           | 2.32e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2818    |
|    iterations      | 58      |
|    time_elapsed    | 674     |
|    total_timesteps | 1900544 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2813         |
|    iterations           | 59           |
|    time_elapsed         | 687          |
|    total_timesteps      | 1933312      |
| train/                  |              |
|    approx_kl            | 0.0067524114 |
|    clip_fraction        | 0.046        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | -0.576       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0152      |
|    n_updates            | 580          |
|    policy_gradient_loss | -0.00695     |
|    value_loss           | 1.13e-05     |
------------------------------------------

Eval num_timesteps=1950000, episode_reward=0.00 +/- 0.00

Episode length: 12.60 +/- 0.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 12.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 1950000     |
| train/                  |             |
|    approx_kl            | 0.007518025 |
|    clip_fraction        | 0.0427      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | -0.757      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0167     |
|    n_updates            | 590         |
|    policy_gradient_loss | -0.00808    |
|    value_loss           | 1.26e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2809    |
|    iterations      | 60      |
|    time_elapsed    | 699     |
|    total_timesteps | 1966080 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2806        |
|    iterations           | 61          |
|    time_elapsed         | 712         |
|    total_timesteps      | 1998848     |
| train/                  |             |
|    approx_kl            | 0.006150925 |
|    clip_fraction        | 0.0515      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | -0.774      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0291     |
|    n_updates            | 600         |
|    policy_gradient_loss | -0.0057     |
|    value_loss           | 6.68e-06    |
-----------------------------------------

Eval num_timesteps=2000000, episode_reward=0.00 +/- 0.00

Episode length: 10.60 +/- 0.49

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 10.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2000000      |
| train/                  |              |
|    approx_kl            | 0.0050718472 |
|    clip_fraction        | 0.0461       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | -0.131       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0326      |
|    n_updates            | 610          |
|    policy_gradient_loss | -0.00556     |
|    value_loss           | 3.33e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2803    |
|    iterations      | 62      |
|    time_elapsed    | 724     |
|    total_timesteps | 2031616 |
--------------------------------

Eval num_timesteps=2050000, episode_reward=0.00 +/- 0.00

Episode length: 8.40 +/- 1.36

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 8.4          |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2050000      |
| train/                  |              |
|    approx_kl            | 0.0062286654 |
|    clip_fraction        | 0.0503       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.191       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0243      |
|    n_updates            | 620          |
|    policy_gradient_loss | -0.00507     |
|    value_loss           | 1.68e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2801    |
|    iterations      | 63      |
|    time_elapsed    | 736     |
|    total_timesteps | 2064384 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2792        |
|    iterations           | 64          |
|    time_elapsed         | 750         |
|    total_timesteps      | 2097152     |
| train/                  |             |
|    approx_kl            | 0.005963754 |
|    clip_fraction        | 0.0367      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.863      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0264     |
|    n_updates            | 630         |
|    policy_gradient_loss | -0.00787    |
|    value_loss           | 1.77e-05    |
-----------------------------------------

Eval num_timesteps=2100000, episode_reward=0.00 +/- 0.00

Episode length: 98.00 +/- 1.10

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2100000     |
| train/                  |             |
|    approx_kl            | 0.005691196 |
|    clip_fraction        | 0.0381      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.0269      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.019      |
|    n_updates            | 640         |
|    policy_gradient_loss | -0.00418    |
|    value_loss           | 1.62e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2789    |
|    iterations      | 65      |
|    time_elapsed    | 763     |
|    total_timesteps | 2129920 |
--------------------------------

Eval num_timesteps=2150000, episode_reward=0.00 +/- 0.00

Episode length: 96.60 +/- 3.26

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2150000      |
| train/                  |              |
|    approx_kl            | 0.0063105244 |
|    clip_fraction        | 0.0399       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | -0.177       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0309      |
|    n_updates            | 650          |
|    policy_gradient_loss | -0.0064      |
|    value_loss           | 3.45e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2779    |
|    iterations      | 66      |
|    time_elapsed    | 778     |
|    total_timesteps | 2162688 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2776        |
|    iterations           | 67          |
|    time_elapsed         | 790         |
|    total_timesteps      | 2195456     |
| train/                  |             |
|    approx_kl            | 0.006185726 |
|    clip_fraction        | 0.0438      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | -1.08       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0252     |
|    n_updates            | 660         |
|    policy_gradient_loss | -0.00707    |
|    value_loss           | 1.93e-05    |
-----------------------------------------

Eval num_timesteps=2200000, episode_reward=0.00 +/- 0.00

Episode length: 99.80 +/- 0.40

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2200000     |
| train/                  |             |
|    approx_kl            | 0.006333803 |
|    clip_fraction        | 0.0489      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.481      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0278     |
|    n_updates            | 670         |
|    policy_gradient_loss | -0.00696    |
|    value_loss           | 6.17e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2773    |
|    iterations      | 68      |
|    time_elapsed    | 803     |
|    total_timesteps | 2228224 |
--------------------------------

Eval num_timesteps=2250000, episode_reward=0.00 +/- 0.00

Episode length: 98.20 +/- 2.64

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2250000     |
| train/                  |             |
|    approx_kl            | 0.012806747 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.235      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0322     |
|    n_updates            | 680         |
|    policy_gradient_loss | -0.00879    |
|    value_loss           | 2.5e-05     |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2769    |
|    iterations      | 69      |
|    time_elapsed    | 816     |
|    total_timesteps | 2260992 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2768        |
|    iterations           | 70          |
|    time_elapsed         | 828         |
|    total_timesteps      | 2293760     |
| train/                  |             |
|    approx_kl            | 0.006895856 |
|    clip_fraction        | 0.0863      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.59       |
|    explained_variance   | -0.169      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.031      |
|    n_updates            | 690         |
|    policy_gradient_loss | -0.00744    |
|    value_loss           | 1e-05       |
-----------------------------------------

Eval num_timesteps=2300000, episode_reward=0.00 +/- 0.00

Episode length: 98.60 +/- 2.33

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 98.6       |
|    mean_reward          | 0          |
| time/                   |            |
|    total_timesteps      | 2300000    |
| train/                  |            |
|    approx_kl            | 0.00710003 |
|    clip_fraction        | 0.0753     |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.6       |
|    explained_variance   | -0.206     |
|    learning_rate        | 0.0001     |
|    loss                 | -0.0141    |
|    n_updates            | 700        |
|    policy_gradient_loss | -0.00764   |
|    value_loss           | 1.07e-05   |
----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2765    |
|    iterations      | 71      |
|    time_elapsed    | 841     |
|    total_timesteps | 2326528 |
--------------------------------

Eval num_timesteps=2350000, episode_reward=0.00 +/- 0.00

Episode length: 97.00 +/- 5.06

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2350000      |
| train/                  |              |
|    approx_kl            | 0.0073807174 |
|    clip_fraction        | 0.0656       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -0.162       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0116      |
|    n_updates            | 710          |
|    policy_gradient_loss | -0.00386     |
|    value_loss           | 1.79e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2763    |
|    iterations      | 72      |
|    time_elapsed    | 853     |
|    total_timesteps | 2359296 |
--------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 2762       |
|    iterations           | 73         |
|    time_elapsed         | 865        |
|    total_timesteps      | 2392064    |
| train/                  |            |
|    approx_kl            | 0.00533526 |
|    clip_fraction        | 0.0434     |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.64      |
|    explained_variance   | -2.21      |
|    learning_rate        | 0.0001     |
|    loss                 | -0.0344    |
|    n_updates            | 720        |
|    policy_gradient_loss | -0.00698   |
|    value_loss           | 2.14e-06   |
----------------------------------------

Eval num_timesteps=2400000, episode_reward=0.00 +/- 0.00

Episode length: 100.00 +/- 0.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 100          |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2400000      |
| train/                  |              |
|    approx_kl            | 0.0063126055 |
|    clip_fraction        | 0.0594       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -0.368       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0249      |
|    n_updates            | 730          |
|    policy_gradient_loss | -0.00384     |
|    value_loss           | 5.32e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2750    |
|    iterations      | 74      |
|    time_elapsed    | 881     |
|    total_timesteps | 2424832 |
--------------------------------

Eval num_timesteps=2450000, episode_reward=0.00 +/- 0.00

Episode length: 95.40 +/- 4.08

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 95.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2450000     |
| train/                  |             |
|    approx_kl            | 0.008259847 |
|    clip_fraction        | 0.0463      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | -0.179      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0232     |
|    n_updates            | 740         |
|    policy_gradient_loss | -0.00633    |
|    value_loss           | 2.43e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2748    |
|    iterations      | 75      |
|    time_elapsed    | 894     |
|    total_timesteps | 2457600 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2747        |
|    iterations           | 76          |
|    time_elapsed         | 906         |
|    total_timesteps      | 2490368     |
| train/                  |             |
|    approx_kl            | 0.008182253 |
|    clip_fraction        | 0.0429      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.58       |
|    explained_variance   | -0.505      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0334     |
|    n_updates            | 750         |
|    policy_gradient_loss | -0.00723    |
|    value_loss           | 5.64e-06    |
-----------------------------------------

Eval num_timesteps=2500000, episode_reward=0.00 +/- 0.00

Episode length: 96.80 +/- 3.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 96.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2500000     |
| train/                  |             |
|    approx_kl            | 0.004415974 |
|    clip_fraction        | 0.0264      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | -0.0193     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0242     |
|    n_updates            | 760         |
|    policy_gradient_loss | -0.00804    |
|    value_loss           | 1.72e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2745    |
|    iterations      | 77      |
|    time_elapsed    | 918     |
|    total_timesteps | 2523136 |
--------------------------------

Eval num_timesteps=2550000, episode_reward=0.00 +/- 0.00

Episode length: 94.20 +/- 5.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 94.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2550000     |
| train/                  |             |
|    approx_kl            | 0.005755871 |
|    clip_fraction        | 0.0254      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.142      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0187     |
|    n_updates            | 770         |
|    policy_gradient_loss | -0.00441    |
|    value_loss           | 4.83e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2744    |
|    iterations      | 78      |
|    time_elapsed    | 931     |
|    total_timesteps | 2555904 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2743        |
|    iterations           | 79          |
|    time_elapsed         | 943         |
|    total_timesteps      | 2588672     |
| train/                  |             |
|    approx_kl            | 0.004590502 |
|    clip_fraction        | 0.03        |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.435      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0253     |
|    n_updates            | 780         |
|    policy_gradient_loss | -0.00789    |
|    value_loss           | 6.44e-06    |
-----------------------------------------

Eval num_timesteps=2600000, episode_reward=0.00 +/- 0.00

Episode length: 99.00 +/- 0.63

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 99         |
|    mean_reward          | 0          |
| time/                   |            |
|    total_timesteps      | 2600000    |
| train/                  |            |
|    approx_kl            | 0.00498915 |
|    clip_fraction        | 0.0324     |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.63      |
|    explained_variance   | 0.11       |
|    learning_rate        | 0.0001     |
|    loss                 | -0.0133    |
|    n_updates            | 790        |
|    policy_gradient_loss | -0.00524   |
|    value_loss           | 3.81e-05   |
----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2741    |
|    iterations      | 80      |
|    time_elapsed    | 956     |
|    total_timesteps | 2621440 |
--------------------------------

Eval num_timesteps=2650000, episode_reward=0.00 +/- 0.00

Episode length: 99.40 +/- 0.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2650000     |
| train/                  |             |
|    approx_kl            | 0.008556135 |
|    clip_fraction        | 0.0579      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.0288      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0281     |
|    n_updates            | 800         |
|    policy_gradient_loss | -0.00739    |
|    value_loss           | 2.31e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2739    |
|    iterations      | 81      |
|    time_elapsed    | 968     |
|    total_timesteps | 2654208 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2739        |
|    iterations           | 82          |
|    time_elapsed         | 980         |
|    total_timesteps      | 2686976     |
| train/                  |             |
|    approx_kl            | 0.005908265 |
|    clip_fraction        | 0.0277      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | 0.194       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.000162   |
|    n_updates            | 810         |
|    policy_gradient_loss | -0.0065     |
|    value_loss           | 2.05e-05    |
-----------------------------------------

Eval num_timesteps=2700000, episode_reward=0.00 +/- 0.00

Episode length: 98.60 +/- 1.85

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 98.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2700000      |
| train/                  |              |
|    approx_kl            | 0.0071286177 |
|    clip_fraction        | 0.0305       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.369        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0329      |
|    n_updates            | 820          |
|    policy_gradient_loss | -0.00674     |
|    value_loss           | 2.34e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2731    |
|    iterations      | 83      |
|    time_elapsed    | 995     |
|    total_timesteps | 2719744 |
--------------------------------

Eval num_timesteps=2750000, episode_reward=0.00 +/- 0.00

Episode length: 97.40 +/- 2.42

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97.4         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2750000      |
| train/                  |              |
|    approx_kl            | 0.0067201946 |
|    clip_fraction        | 0.0446       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.537        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0263      |
|    n_updates            | 830          |
|    policy_gradient_loss | -0.00515     |
|    value_loss           | 2.63e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2730    |
|    iterations      | 84      |
|    time_elapsed    | 1008    |
|    total_timesteps | 2752512 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2727        |
|    iterations           | 85          |
|    time_elapsed         | 1021        |
|    total_timesteps      | 2785280     |
| train/                  |             |
|    approx_kl            | 0.007742295 |
|    clip_fraction        | 0.0455      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.604       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0249     |
|    n_updates            | 840         |
|    policy_gradient_loss | -0.00745    |
|    value_loss           | 2.44e-05    |
-----------------------------------------

Eval num_timesteps=2800000, episode_reward=0.00 +/- 0.00

Episode length: 97.60 +/- 2.15

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2800000      |
| train/                  |              |
|    approx_kl            | 0.0055011776 |
|    clip_fraction        | 0.0516       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.67        |
|    explained_variance   | 0.323        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0102      |
|    n_updates            | 850          |
|    policy_gradient_loss | -0.00322     |
|    value_loss           | 4.18e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2726    |
|    iterations      | 86      |
|    time_elapsed    | 1033    |
|    total_timesteps | 2818048 |
--------------------------------

Eval num_timesteps=2850000, episode_reward=0.00 +/- 0.00

Episode length: 98.40 +/- 1.85

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2850000     |
| train/                  |             |
|    approx_kl            | 0.006087085 |
|    clip_fraction        | 0.0625      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | -0.000462   |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0198     |
|    n_updates            | 860         |
|    policy_gradient_loss | -0.00763    |
|    value_loss           | 1.03e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2724    |
|    iterations      | 87      |
|    time_elapsed    | 1046    |
|    total_timesteps | 2850816 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2723         |
|    iterations           | 88           |
|    time_elapsed         | 1058         |
|    total_timesteps      | 2883584      |
| train/                  |              |
|    approx_kl            | 0.0046980856 |
|    clip_fraction        | 0.0327       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.251        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0324      |
|    n_updates            | 870          |
|    policy_gradient_loss | -0.00735     |
|    value_loss           | 1.32e-05     |
------------------------------------------

Eval num_timesteps=2900000, episode_reward=0.00 +/- 0.00

Episode length: 99.60 +/- 0.49

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 99.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 2900000     |
| train/                  |             |
|    approx_kl            | 0.005691256 |
|    clip_fraction        | 0.0365      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.567       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0239     |
|    n_updates            | 880         |
|    policy_gradient_loss | -0.00542    |
|    value_loss           | 7.53e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2722    |
|    iterations      | 89      |
|    time_elapsed    | 1071    |
|    total_timesteps | 2916352 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2721        |
|    iterations           | 90          |
|    time_elapsed         | 1083        |
|    total_timesteps      | 2949120     |
| train/                  |             |
|    approx_kl            | 0.007618089 |
|    clip_fraction        | 0.0681      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | -0.0382     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0268     |
|    n_updates            | 890         |
|    policy_gradient_loss | -0.00733    |
|    value_loss           | 2.45e-06    |
-----------------------------------------

Eval num_timesteps=2950000, episode_reward=0.00 +/- 0.00

Episode length: 96.20 +/- 2.79

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 2950000      |
| train/                  |              |
|    approx_kl            | 0.0048062466 |
|    clip_fraction        | 0.0298       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.558        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0221      |
|    n_updates            | 900          |
|    policy_gradient_loss | -0.00677     |
|    value_loss           | 5.22e-07     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2715    |
|    iterations      | 91      |
|    time_elapsed    | 1098    |
|    total_timesteps | 2981888 |
--------------------------------

Eval num_timesteps=3000000, episode_reward=0.00 +/- 0.00

Episode length: 98.60 +/- 1.85

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 98.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3000000      |
| train/                  |              |
|    approx_kl            | 0.0045989617 |
|    clip_fraction        | 0.0228       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.469       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0227      |
|    n_updates            | 910          |
|    policy_gradient_loss | -0.00755     |
|    value_loss           | 2.92e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2714    |
|    iterations      | 92      |
|    time_elapsed    | 1110    |
|    total_timesteps | 3014656 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2713         |
|    iterations           | 93           |
|    time_elapsed         | 1122         |
|    total_timesteps      | 3047424      |
| train/                  |              |
|    approx_kl            | 0.0073922654 |
|    clip_fraction        | 0.0759       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.103       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0233      |
|    n_updates            | 920          |
|    policy_gradient_loss | -0.00815     |
|    value_loss           | 1.28e-05     |
------------------------------------------

Eval num_timesteps=3050000, episode_reward=0.00 +/- 0.00

Episode length: 98.00 +/- 2.61

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 98           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3050000      |
| train/                  |              |
|    approx_kl            | 0.0063363723 |
|    clip_fraction        | 0.0324       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.0271      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0279      |
|    n_updates            | 930          |
|    policy_gradient_loss | -0.00945     |
|    value_loss           | 1.83e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2712    |
|    iterations      | 94      |
|    time_elapsed    | 1135    |
|    total_timesteps | 3080192 |
--------------------------------

Eval num_timesteps=3100000, episode_reward=0.00 +/- 0.00

Episode length: 96.40 +/- 4.13

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.4         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3100000      |
| train/                  |              |
|    approx_kl            | 0.0054872693 |
|    clip_fraction        | 0.0387       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.118        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0169      |
|    n_updates            | 940          |
|    policy_gradient_loss | -0.0081      |
|    value_loss           | 2.89e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2711    |
|    iterations      | 95      |
|    time_elapsed    | 1148    |
|    total_timesteps | 3112960 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2710         |
|    iterations           | 96           |
|    time_elapsed         | 1160         |
|    total_timesteps      | 3145728      |
| train/                  |              |
|    approx_kl            | 0.0063609285 |
|    clip_fraction        | 0.0445       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -1.28        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0185      |
|    n_updates            | 950          |
|    policy_gradient_loss | -0.00753     |
|    value_loss           | 2.96e-06     |
------------------------------------------

Eval num_timesteps=3150000, episode_reward=0.00 +/- 0.00

Episode length: 95.80 +/- 4.02

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 95.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3150000      |
| train/                  |              |
|    approx_kl            | 0.0050092097 |
|    clip_fraction        | 0.0361       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | -0.423       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0243      |
|    n_updates            | 960          |
|    policy_gradient_loss | -0.00802     |
|    value_loss           | 6.3e-06      |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2709    |
|    iterations      | 97      |
|    time_elapsed    | 1172    |
|    total_timesteps | 3178496 |
--------------------------------

Eval num_timesteps=3200000, episode_reward=0.00 +/- 0.00

Episode length: 96.80 +/- 4.53

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.8         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3200000      |
| train/                  |              |
|    approx_kl            | 0.0072702076 |
|    clip_fraction        | 0.064        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.254        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0192      |
|    n_updates            | 970          |
|    policy_gradient_loss | -0.00842     |
|    value_loss           | 1.45e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2708    |
|    iterations      | 98      |
|    time_elapsed    | 1185    |
|    total_timesteps | 3211264 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2708         |
|    iterations           | 99           |
|    time_elapsed         | 1197         |
|    total_timesteps      | 3244032      |
| train/                  |              |
|    approx_kl            | 0.0062814783 |
|    clip_fraction        | 0.0691       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.121        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.00754     |
|    n_updates            | 980          |
|    policy_gradient_loss | -0.00673     |
|    value_loss           | 1.36e-05     |
------------------------------------------

Eval num_timesteps=3250000, episode_reward=0.00 +/- 0.00

Episode length: 97.40 +/- 4.72

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3250000     |
| train/                  |             |
|    approx_kl            | 0.006925408 |
|    clip_fraction        | 0.0547      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | -0.127      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0246     |
|    n_updates            | 990         |
|    policy_gradient_loss | -0.00896    |
|    value_loss           | 4.89e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2702    |
|    iterations      | 100     |
|    time_elapsed    | 1212    |
|    total_timesteps | 3276800 |
--------------------------------

Eval num_timesteps=3300000, episode_reward=0.00 +/- 0.00

Episode length: 98.20 +/- 1.83

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 98.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3300000      |
| train/                  |              |
|    approx_kl            | 0.0057153143 |
|    clip_fraction        | 0.0404       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.366        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0235      |
|    n_updates            | 1000         |
|    policy_gradient_loss | -0.00776     |
|    value_loss           | 3.83e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2698    |
|    iterations      | 101     |
|    time_elapsed    | 1226    |
|    total_timesteps | 3309568 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2698         |
|    iterations           | 102          |
|    time_elapsed         | 1238         |
|    total_timesteps      | 3342336      |
| train/                  |              |
|    approx_kl            | 0.0072765476 |
|    clip_fraction        | 0.0607       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | 0.525        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0316      |
|    n_updates            | 1010         |
|    policy_gradient_loss | -0.00682     |
|    value_loss           | 2.57e-06     |
------------------------------------------

Eval num_timesteps=3350000, episode_reward=0.00 +/- 0.00

Episode length: 97.20 +/- 5.11

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3350000     |
| train/                  |             |
|    approx_kl            | 0.008096699 |
|    clip_fraction        | 0.0708      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.00251    |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0304     |
|    n_updates            | 1020        |
|    policy_gradient_loss | -0.00796    |
|    value_loss           | 1.19e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2696    |
|    iterations      | 103     |
|    time_elapsed    | 1251    |
|    total_timesteps | 3375104 |
--------------------------------

Eval num_timesteps=3400000, episode_reward=0.00 +/- 0.00

Episode length: 97.20 +/- 3.06

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3400000     |
| train/                  |             |
|    approx_kl            | 0.006452843 |
|    clip_fraction        | 0.0436      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -1.03       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0295     |
|    n_updates            | 1030        |
|    policy_gradient_loss | -0.00716    |
|    value_loss           | 1.44e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2695    |
|    iterations      | 104     |
|    time_elapsed    | 1264    |
|    total_timesteps | 3407872 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2695        |
|    iterations           | 105         |
|    time_elapsed         | 1276        |
|    total_timesteps      | 3440640     |
| train/                  |             |
|    approx_kl            | 0.006659806 |
|    clip_fraction        | 0.0462      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.0736     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0235     |
|    n_updates            | 1040        |
|    policy_gradient_loss | -0.00854    |
|    value_loss           | 7.94e-06    |
-----------------------------------------

Eval num_timesteps=3450000, episode_reward=0.00 +/- 0.00

Episode length: 96.80 +/- 2.93

--------------------------------
| time/              |         |
|    fps             | 2694    |
|    iterations      | 106     |
|    time_elapsed    | 1289    |
|    total_timesteps | 3473408 |
--------------------------------

Eval num_timesteps=3500000, episode_reward=0.00 +/- 0.00

Episode length: 96.20 +/- 2.79

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 96.2        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3500000     |
| train/                  |             |
|    approx_kl            | 0.005996081 |
|    clip_fraction        | 0.0524      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | -0.00244    |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0246     |
|    n_updates            | 1060        |
|    policy_gradient_loss | -0.0063     |
|    value_loss           | 6.69e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2692    |
|    iterations      | 107     |
|    time_elapsed    | 1302    |
|    total_timesteps | 3506176 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2691        |
|    iterations           | 108         |
|    time_elapsed         | 1314        |
|    total_timesteps      | 3538944     |
| train/                  |             |
|    approx_kl            | 0.006910023 |
|    clip_fraction        | 0.0524      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.0545      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0299     |
|    n_updates            | 1070        |
|    policy_gradient_loss | -0.00763    |
|    value_loss           | 1.32e-05    |
-----------------------------------------

Eval num_timesteps=3550000, episode_reward=0.00 +/- 0.00

Episode length: 99.00 +/- 0.63

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 99           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3550000      |
| train/                  |              |
|    approx_kl            | 0.0071698837 |
|    clip_fraction        | 0.0675       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | -0.0289      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0327      |
|    n_updates            | 1080         |
|    policy_gradient_loss | -0.00632     |
|    value_loss           | 6.06e-07     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2685    |
|    iterations      | 109     |
|    time_elapsed    | 1329    |
|    total_timesteps | 3571712 |
--------------------------------

Eval num_timesteps=3600000, episode_reward=0.00 +/- 0.00

Episode length: 96.60 +/- 3.98

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3600000      |
| train/                  |              |
|    approx_kl            | 0.0065414514 |
|    clip_fraction        | 0.052        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -2.9         |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0242      |
|    n_updates            | 1090         |
|    policy_gradient_loss | -0.00878     |
|    value_loss           | 7.72e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2684    |
|    iterations      | 110     |
|    time_elapsed    | 1342    |
|    total_timesteps | 3604480 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2683         |
|    iterations           | 111          |
|    time_elapsed         | 1355         |
|    total_timesteps      | 3637248      |
| train/                  |              |
|    approx_kl            | 0.0056236275 |
|    clip_fraction        | 0.0458       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -0.341       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.034       |
|    n_updates            | 1100         |
|    policy_gradient_loss | -0.00706     |
|    value_loss           | 3.72e-06     |
------------------------------------------

Eval num_timesteps=3650000, episode_reward=-0.00 +/- 0.00

Episode length: 96.80 +/- 2.40

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.8         |
|    mean_reward          | -0.00086     |
| time/                   |              |
|    total_timesteps      | 3650000      |
| train/                  |              |
|    approx_kl            | 0.0067928093 |
|    clip_fraction        | 0.0447       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.61        |
|    explained_variance   | -0.448       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0215      |
|    n_updates            | 1110         |
|    policy_gradient_loss | -0.00667     |
|    value_loss           | 6.83e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2681    |
|    iterations      | 112     |
|    time_elapsed    | 1368    |
|    total_timesteps | 3670016 |
--------------------------------

Eval num_timesteps=3700000, episode_reward=0.00 +/- 0.00

Episode length: 92.20 +/- 9.06

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 92.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3700000      |
| train/                  |              |
|    approx_kl            | 0.0069878516 |
|    clip_fraction        | 0.0483       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -0.118       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0285      |
|    n_updates            | 1120         |
|    policy_gradient_loss | -0.00796     |
|    value_loss           | 1.98e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2680    |
|    iterations      | 113     |
|    time_elapsed    | 1381    |
|    total_timesteps | 3702784 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2679        |
|    iterations           | 114         |
|    time_elapsed         | 1393        |
|    total_timesteps      | 3735552     |
| train/                  |             |
|    approx_kl            | 0.010061149 |
|    clip_fraction        | 0.0941      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | -0.141      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0258     |
|    n_updates            | 1130        |
|    policy_gradient_loss | -0.00653    |
|    value_loss           | 2.18e-05    |
-----------------------------------------

Eval num_timesteps=3750000, episode_reward=0.00 +/- 0.00

Episode length: 98.20 +/- 1.33

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 98.2       |
|    mean_reward          | 0          |
| time/                   |            |
|    total_timesteps      | 3750000    |
| train/                  |            |
|    approx_kl            | 0.00539118 |
|    clip_fraction        | 0.0358     |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.62      |
|    explained_variance   | -0.361     |
|    learning_rate        | 0.0001     |
|    loss                 | -0.0133    |
|    n_updates            | 1140       |
|    policy_gradient_loss | -0.00745   |
|    value_loss           | 0.000129   |
----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2678    |
|    iterations      | 115     |
|    time_elapsed    | 1407    |
|    total_timesteps | 3768320 |
--------------------------------

Eval num_timesteps=3800000, episode_reward=0.00 +/- 0.00

Episode length: 95.60 +/- 2.80

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 95.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 3800000      |
| train/                  |              |
|    approx_kl            | 0.0071941074 |
|    clip_fraction        | 0.055        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.186        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0319      |
|    n_updates            | 1150         |
|    policy_gradient_loss | -0.00646     |
|    value_loss           | 5.96e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2677    |
|    iterations      | 116     |
|    time_elapsed    | 1419    |
|    total_timesteps | 3801088 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2676         |
|    iterations           | 117          |
|    time_elapsed         | 1432         |
|    total_timesteps      | 3833856      |
| train/                  |              |
|    approx_kl            | 0.0052490775 |
|    clip_fraction        | 0.0541       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.59        |
|    explained_variance   | 0.12         |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0252      |
|    n_updates            | 1160         |
|    policy_gradient_loss | -0.00649     |
|    value_loss           | 8.52e-06     |
------------------------------------------

Eval num_timesteps=3850000, episode_reward=0.00 +/- 0.00

Episode length: 98.00 +/- 2.10

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3850000     |
| train/                  |             |
|    approx_kl            | 0.005445234 |
|    clip_fraction        | 0.0345      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | -0.0783     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.025      |
|    n_updates            | 1170        |
|    policy_gradient_loss | -0.00908    |
|    value_loss           | 2.5e-06     |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2676    |
|    iterations      | 118     |
|    time_elapsed    | 1444    |
|    total_timesteps | 3866624 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2678         |
|    iterations           | 119          |
|    time_elapsed         | 1455         |
|    total_timesteps      | 3899392      |
| train/                  |              |
|    approx_kl            | 0.0072536296 |
|    clip_fraction        | 0.0461       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.58        |
|    explained_variance   | -0.542       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0249      |
|    n_updates            | 1180         |
|    policy_gradient_loss | -0.00765     |
|    value_loss           | 4.41e-06     |
------------------------------------------

Eval num_timesteps=3900000, episode_reward=0.00 +/- 0.00

Episode length: 97.60 +/- 3.83

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.6        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3900000     |
| train/                  |             |
|    approx_kl            | 0.006643404 |
|    clip_fraction        | 0.0654      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.59       |
|    explained_variance   | -0.608      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0257     |
|    n_updates            | 1190        |
|    policy_gradient_loss | -0.00826    |
|    value_loss           | 5.92e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2680    |
|    iterations      | 120     |
|    time_elapsed    | 1467    |
|    total_timesteps | 3932160 |
--------------------------------

Eval num_timesteps=3950000, episode_reward=0.00 +/- 0.00

Episode length: 98.00 +/- 2.61

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 3950000     |
| train/                  |             |
|    approx_kl            | 0.008029291 |
|    clip_fraction        | 0.0878      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | -0.218      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0134     |
|    n_updates            | 1200        |
|    policy_gradient_loss | -0.00496    |
|    value_loss           | 5.85e-06    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2681    |
|    iterations      | 121     |
|    time_elapsed    | 1478    |
|    total_timesteps | 3964928 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2684         |
|    iterations           | 122          |
|    time_elapsed         | 1489         |
|    total_timesteps      | 3997696      |
| train/                  |              |
|    approx_kl            | 0.0070079686 |
|    clip_fraction        | 0.0805       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.56        |
|    explained_variance   | -1.55        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0293      |
|    n_updates            | 1210         |
|    policy_gradient_loss | -0.00885     |
|    value_loss           | 2.19e-05     |
------------------------------------------

Eval num_timesteps=4000000, episode_reward=0.00 +/- 0.00

Episode length: 96.60 +/- 3.38

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4000000      |
| train/                  |              |
|    approx_kl            | 0.0057883025 |
|    clip_fraction        | 0.0326       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -0.0847      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.00906     |
|    n_updates            | 1220         |
|    policy_gradient_loss | -0.00568     |
|    value_loss           | 3.33e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2686    |
|    iterations      | 123     |
|    time_elapsed    | 1500    |
|    total_timesteps | 4030464 |
--------------------------------

Eval num_timesteps=4050000, episode_reward=0.00 +/- 0.00

Episode length: 96.40 +/- 3.93

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.4         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4050000      |
| train/                  |              |
|    approx_kl            | 0.0051517775 |
|    clip_fraction        | 0.02         |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -0.206       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0293      |
|    n_updates            | 1230         |
|    policy_gradient_loss | -0.00732     |
|    value_loss           | 1.79e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2688    |
|    iterations      | 124     |
|    time_elapsed    | 1511    |
|    total_timesteps | 4063232 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2691        |
|    iterations           | 125         |
|    time_elapsed         | 1522        |
|    total_timesteps      | 4096000     |
| train/                  |             |
|    approx_kl            | 0.005279316 |
|    clip_fraction        | 0.0247      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.221       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0191     |
|    n_updates            | 1240        |
|    policy_gradient_loss | -0.00569    |
|    value_loss           | 5.98e-05    |
-----------------------------------------

Eval num_timesteps=4100000, episode_reward=0.00 +/- 0.00

Episode length: 96.80 +/- 2.93

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 96.8        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 4100000     |
| train/                  |             |
|    approx_kl            | 0.005358384 |
|    clip_fraction        | 0.0303      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.703       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0295     |
|    n_updates            | 1250        |
|    policy_gradient_loss | -0.00744    |
|    value_loss           | 1.54e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2693    |
|    iterations      | 126     |
|    time_elapsed    | 1533    |
|    total_timesteps | 4128768 |
--------------------------------

Eval num_timesteps=4150000, episode_reward=0.00 +/- 0.00

Episode length: 99.20 +/- 0.75

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 99.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4150000      |
| train/                  |              |
|    approx_kl            | 0.0049222438 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.255        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0188      |
|    n_updates            | 1260         |
|    policy_gradient_loss | -0.00525     |
|    value_loss           | 1.77e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2691    |
|    iterations      | 127     |
|    time_elapsed    | 1546    |
|    total_timesteps | 4161536 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2693        |
|    iterations           | 128         |
|    time_elapsed         | 1557        |
|    total_timesteps      | 4194304     |
| train/                  |             |
|    approx_kl            | 0.006206858 |
|    clip_fraction        | 0.0454      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.208      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0232     |
|    n_updates            | 1270        |
|    policy_gradient_loss | -0.00867    |
|    value_loss           | 1.07e-05    |
-----------------------------------------

Eval num_timesteps=4200000, episode_reward=0.00 +/- 0.00

Episode length: 97.00 +/- 2.97

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4200000      |
| train/                  |              |
|    approx_kl            | 0.0048528756 |
|    clip_fraction        | 0.0265       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | -0.846       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0151      |
|    n_updates            | 1280         |
|    policy_gradient_loss | -0.007       |
|    value_loss           | 8.05e-06     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2695    |
|    iterations      | 129     |
|    time_elapsed    | 1568    |
|    total_timesteps | 4227072 |
--------------------------------

Eval num_timesteps=4250000, episode_reward=0.00 +/- 0.00

Episode length: 97.00 +/- 2.61

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 4250000     |
| train/                  |             |
|    approx_kl            | 0.005515945 |
|    clip_fraction        | 0.0187      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.292       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0235     |
|    n_updates            | 1290        |
|    policy_gradient_loss | -0.0046     |
|    value_loss           | 1.43e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2697    |
|    iterations      | 130     |
|    time_elapsed    | 1578    |
|    total_timesteps | 4259840 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2700        |
|    iterations           | 131         |
|    time_elapsed         | 1589        |
|    total_timesteps      | 4292608     |
| train/                  |             |
|    approx_kl            | 0.029519485 |
|    clip_fraction        | 0.0498      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.266       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0321     |
|    n_updates            | 1300        |
|    policy_gradient_loss | -0.0138     |
|    value_loss           | 6.97e-06    |
-----------------------------------------

Eval num_timesteps=4300000, episode_reward=0.01 +/- 0.02

Episode length: 98.00 +/- 1.90

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98          |
|    mean_reward          | 0.00962     |
| time/                   |             |
|    total_timesteps      | 4300000     |
| train/                  |             |
|    approx_kl            | 0.008703234 |
|    clip_fraction        | 0.0511      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.0858     |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0271     |
|    n_updates            | 1310        |
|    policy_gradient_loss | -0.00627    |
|    value_loss           | 0.000138    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2702    |
|    iterations      | 132     |
|    time_elapsed    | 1600    |
|    total_timesteps | 4325376 |
--------------------------------

Eval num_timesteps=4350000, episode_reward=0.00 +/- 0.00

Episode length: 99.20 +/- 0.75

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 99.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4350000      |
| train/                  |              |
|    approx_kl            | 0.0059764925 |
|    clip_fraction        | 0.0316       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -0.0649      |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0283      |
|    n_updates            | 1320         |
|    policy_gradient_loss | -0.00603     |
|    value_loss           | 9.2e-05      |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2703    |
|    iterations      | 133     |
|    time_elapsed    | 1611    |
|    total_timesteps | 4358144 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2706         |
|    iterations           | 134          |
|    time_elapsed         | 1622         |
|    total_timesteps      | 4390912      |
| train/                  |              |
|    approx_kl            | 0.0035502166 |
|    clip_fraction        | 0.0189       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.108       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0306      |
|    n_updates            | 1330         |
|    policy_gradient_loss | -0.00613     |
|    value_loss           | 0.00014      |
------------------------------------------

Eval num_timesteps=4400000, episode_reward=0.00 +/- 0.00

Episode length: 97.40 +/- 2.80

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 97.4        |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 4400000     |
| train/                  |             |
|    approx_kl            | 0.006009957 |
|    clip_fraction        | 0.0331      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | 0.101       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0306     |
|    n_updates            | 1340        |
|    policy_gradient_loss | -0.00593    |
|    value_loss           | 3.38e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2708    |
|    iterations      | 135     |
|    time_elapsed    | 1633    |
|    total_timesteps | 4423680 |
--------------------------------

Eval num_timesteps=4450000, episode_reward=0.00 +/- 0.00

Episode length: 97.00 +/- 3.35

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 97           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4450000      |
| train/                  |              |
|    approx_kl            | 0.0049899304 |
|    clip_fraction        | 0.0372       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -0.058       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.00574     |
|    n_updates            | 1350         |
|    policy_gradient_loss | -0.00685     |
|    value_loss           | 2.77e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2707    |
|    iterations      | 136     |
|    time_elapsed    | 1646    |
|    total_timesteps | 4456448 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2710        |
|    iterations           | 137         |
|    time_elapsed         | 1656        |
|    total_timesteps      | 4489216     |
| train/                  |             |
|    approx_kl            | 0.005151004 |
|    clip_fraction        | 0.0267      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.0633      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0206     |
|    n_updates            | 1360        |
|    policy_gradient_loss | -0.00564    |
|    value_loss           | 0.000123    |
-----------------------------------------

Eval num_timesteps=4500000, episode_reward=0.10 +/- 0.20

Episode length: 96.60 +/- 3.01

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 96.6         |
|    mean_reward          | 0.102        |
| time/                   |              |
|    total_timesteps      | 4500000      |
| train/                  |              |
|    approx_kl            | 0.0064371037 |
|    clip_fraction        | 0.0408       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | -0.19        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0187      |
|    n_updates            | 1370         |
|    policy_gradient_loss | -0.00594     |
|    value_loss           | 8.07e-05     |
------------------------------------------

New best mean reward!

--------------------------------
| time/              |         |
|    fps             | 2713    |
|    iterations      | 138     |
|    time_elapsed    | 1666    |
|    total_timesteps | 4521984 |
--------------------------------

Eval num_timesteps=4550000, episode_reward=0.00 +/- 0.00

Episode length: 96.00 +/- 3.41

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 96          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 4550000     |
| train/                  |             |
|    approx_kl            | 0.008844132 |
|    clip_fraction        | 0.0405      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | -0.228      |
|    learning_rate        | 0.0001      |
|    loss                 | 0.00102     |
|    n_updates            | 1380        |
|    policy_gradient_loss | -0.00698    |
|    value_loss           | 9.08e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2715    |
|    iterations      | 139     |
|    time_elapsed    | 1677    |
|    total_timesteps | 4554752 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2718         |
|    iterations           | 140          |
|    time_elapsed         | 1687         |
|    total_timesteps      | 4587520      |
| train/                  |              |
|    approx_kl            | 0.0070927134 |
|    clip_fraction        | 0.056        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.6         |
|    explained_variance   | 0.0849       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0218      |
|    n_updates            | 1390         |
|    policy_gradient_loss | -0.00519     |
|    value_loss           | 0.000358     |
------------------------------------------

Eval num_timesteps=4600000, episode_reward=0.00 +/- 0.00

Episode length: 98.40 +/- 2.24

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 98.4         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4600000      |
| train/                  |              |
|    approx_kl            | 0.0045706686 |
|    clip_fraction        | 0.0253       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.029        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0313      |
|    n_updates            | 1400         |
|    policy_gradient_loss | -0.00683     |
|    value_loss           | 7.52e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2721    |
|    iterations      | 141     |
|    time_elapsed    | 1697    |
|    total_timesteps | 4620288 |
--------------------------------

Eval num_timesteps=4650000, episode_reward=0.00 +/- 0.00

Episode length: 98.00 +/- 3.10

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 98          |
|    mean_reward          | 0           |
| time/                   |             |
|    total_timesteps      | 4650000     |
| train/                  |             |
|    approx_kl            | 0.004836141 |
|    clip_fraction        | 0.0265      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.0667      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0245     |
|    n_updates            | 1410        |
|    policy_gradient_loss | -0.00647    |
|    value_loss           | 0.000147    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2723    |
|    iterations      | 142     |
|    time_elapsed    | 1708    |
|    total_timesteps | 4653056 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2724         |
|    iterations           | 143          |
|    time_elapsed         | 1719         |
|    total_timesteps      | 4685824      |
| train/                  |              |
|    approx_kl            | 0.0073904237 |
|    clip_fraction        | 0.0303       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.59        |
|    explained_variance   | 0.0999       |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0264      |
|    n_updates            | 1420         |
|    policy_gradient_loss | -0.00555     |
|    value_loss           | 0.00026      |
------------------------------------------

Eval num_timesteps=4700000, episode_reward=0.00 +/- 0.00

Episode length: 92.60 +/- 5.08

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 92.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4700000      |
| train/                  |              |
|    approx_kl            | 0.0053304355 |
|    clip_fraction        | 0.023        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | 0.305        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0245      |
|    n_updates            | 1430         |
|    policy_gradient_loss | -0.00529     |
|    value_loss           | 0.00025      |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2720    |
|    iterations      | 144     |
|    time_elapsed    | 1734    |
|    total_timesteps | 4718592 |
--------------------------------

Eval num_timesteps=4750000, episode_reward=0.00 +/- 0.00

Episode length: 86.80 +/- 3.54

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 86.8        |
|    mean_reward          | 0.00123     |
| time/                   |             |
|    total_timesteps      | 4750000     |
| train/                  |             |
|    approx_kl            | 0.005141096 |
|    clip_fraction        | 0.0234      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.287       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0298     |
|    n_updates            | 1440        |
|    policy_gradient_loss | -0.00634    |
|    value_loss           | 9.75e-05    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2719    |
|    iterations      | 145     |
|    time_elapsed    | 1747    |
|    total_timesteps | 4751360 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2719         |
|    iterations           | 146          |
|    time_elapsed         | 1759         |
|    total_timesteps      | 4784128      |
| train/                  |              |
|    approx_kl            | 0.0074060326 |
|    clip_fraction        | 0.0259       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.62        |
|    explained_variance   | -1.41        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0266      |
|    n_updates            | 1450         |
|    policy_gradient_loss | -0.0034      |
|    value_loss           | 0.000146     |
------------------------------------------

Eval num_timesteps=4800000, episode_reward=-0.00 +/- 0.01

Episode length: 74.80 +/- 1.60

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 74.8        |
|    mean_reward          | -0.00443    |
| time/                   |             |
|    total_timesteps      | 4800000     |
| train/                  |             |
|    approx_kl            | 0.007495036 |
|    clip_fraction        | 0.0337      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.61       |
|    explained_variance   | 0.182       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0212     |
|    n_updates            | 1460        |
|    policy_gradient_loss | -0.00826    |
|    value_loss           | 0.00011     |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2718    |
|    iterations      | 147     |
|    time_elapsed    | 1772    |
|    total_timesteps | 4816896 |
--------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2717         |
|    iterations           | 148          |
|    time_elapsed         | 1784         |
|    total_timesteps      | 4849664      |
| train/                  |              |
|    approx_kl            | 0.0076950295 |
|    clip_fraction        | 0.0428       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.6         |
|    explained_variance   | 0.268        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0282      |
|    n_updates            | 1470         |
|    policy_gradient_loss | -0.00558     |
|    value_loss           | 0.000122     |
------------------------------------------

Eval num_timesteps=4850000, episode_reward=-0.03 +/- 0.04

Episode length: 65.60 +/- 3.56

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 65.6        |
|    mean_reward          | -0.0285     |
| time/                   |             |
|    total_timesteps      | 4850000     |
| train/                  |             |
|    approx_kl            | 0.006590007 |
|    clip_fraction        | 0.0399      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.127       |
|    learning_rate        | 0.0001      |
|    loss                 | -0.0148     |
|    n_updates            | 1480        |
|    policy_gradient_loss | -0.00614    |
|    value_loss           | 0.000194    |
-----------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2717    |
|    iterations      | 149     |
|    time_elapsed    | 1796    |
|    total_timesteps | 4882432 |
--------------------------------

Eval num_timesteps=4900000, episode_reward=0.00 +/- 0.00

Episode length: 63.00 +/- 1.67

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 63           |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4900000      |
| train/                  |              |
|    approx_kl            | 0.0056338888 |
|    clip_fraction        | 0.0215       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | 0.39         |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0197      |
|    n_updates            | 1490         |
|    policy_gradient_loss | -0.00503     |
|    value_loss           | 6.36e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2716    |
|    iterations      | 150     |
|    time_elapsed    | 1809    |
|    total_timesteps | 4915200 |
--------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2716        |
|    iterations           | 151         |
|    time_elapsed         | 1821        |
|    total_timesteps      | 4947968     |
| train/                  |             |
|    approx_kl            | 0.004817088 |
|    clip_fraction        | 0.017       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | -0.248      |
|    learning_rate        | 0.0001      |
|    loss                 | -0.032      |
|    n_updates            | 1500        |
|    policy_gradient_loss | -0.00449    |
|    value_loss           | 6.33e-05    |
-----------------------------------------

Eval num_timesteps=4950000, episode_reward=0.00 +/- 0.00

Episode length: 55.20 +/- 3.25

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 55.2         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 4950000      |
| train/                  |              |
|    approx_kl            | 0.0049452297 |
|    clip_fraction        | 0.0256       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.278        |
|    learning_rate        | 0.0001       |
|    loss                 | -0.0206      |
|    n_updates            | 1510         |
|    policy_gradient_loss | -0.00744     |
|    value_loss           | 3.93e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2715    |
|    iterations      | 152     |
|    time_elapsed    | 1833    |
|    total_timesteps | 4980736 |
--------------------------------

Eval num_timesteps=5000000, episode_reward=0.00 +/- 0.00

Episode length: 55.60 +/- 1.62

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 55.6         |
|    mean_reward          | 0            |
| time/                   |              |
|    total_timesteps      | 5000000      |
| train/                  |              |
|    approx_kl            | 0.0057260096 |
|    clip_fraction        | 0.0233       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | -0.222       |
|    learning_rate        | 0.0001       |
|    loss                 | 0.036        |
|    n_updates            | 1520         |
|    policy_gradient_loss | -0.00315     |
|    value_loss           | 1.99e-05     |
------------------------------------------
--------------------------------
| time/              |         |
|    fps             | 2711    |
|    iterations      | 153     |
|    time_elapsed    | 1849    |
|    total_timesteps | 5013504 |
--------------------------------

Saved final PPO model to polymarket_output_rl_tuned/ppo_polymarket_trader
Loaded best validation model from polymarket_output_rl_tuned/best_model/best_model.zip

In [18]:
def compute_metrics_from_trades(trades: pd.DataFrame) -> Tuple[pd.DataFrame, Dict[str, float]]:
    if trades.empty:
        return pd.DataFrame(), {
            "cumulative_return": np.nan,
            "annualized_sharpe": np.nan,
            "max_drawdown": np.nan,
            "avg_trade_fraction": np.nan,
            "num_trades": 0,
            "num_steps": 0,
            "num_markets": 0,
            "final_portfolio_value": np.nan,
        }

    trades = trades.sort_values(["market_id", "timestamp"]).reset_index(drop=True)

    trades["step_portfolio_return"] = (
        trades.groupby("market_id")["portfolio_value"]
        .pct_change()
        .replace([np.inf, -np.inf], np.nan)
        .fillna(0.0)
    )

    periods_per_year = (
        24 * 365
        if CONFIG["fidelity"] <= 60
        else max(int((60 / CONFIG["fidelity"]) * 24 * 365), 1)
    )

    per_market_metrics: List[Dict[str, float]] = []
    for market_id, g in trades.groupby("market_id", sort=False):
        g = g.sort_values("timestamp").reset_index(drop=True)

        initial_value = float(g["portfolio_value"].iloc[0])
        final_value = float(g["portfolio_value"].iloc[-1])
        episode_return = final_value / max(initial_value, 1e-8) - 1.0

        equity = g["portfolio_value"].to_numpy(dtype=float)
        running_peak = np.maximum.accumulate(equity)
        dd = equity / np.clip(running_peak, 1e-8, None) - 1.0
        episode_max_drawdown = float(dd.min())

        step_returns = g["step_portfolio_return"].to_numpy(dtype=float)
        step_returns = step_returns[np.isfinite(step_returns)]

        if len(step_returns) > 1 and np.std(step_returns, ddof=1) > 1e-12:
            episode_sharpe = float(
                np.sqrt(periods_per_year) * np.mean(step_returns) / np.std(step_returns, ddof=1)
            )
        else:
            episode_sharpe = np.nan

        executed_mask_g = g["trade_notional"] > 0
        avg_trade_fraction_g = float(
            (
                g.loc[executed_mask_g, "trade_notional"]
                / g.loc[executed_mask_g, "portfolio_value"].clip(lower=1e-8)
            ).mean()
        ) if executed_mask_g.any() else 0.0

        per_market_metrics.append({
            "market_id": market_id,
            "initial_value": initial_value,
            "final_value": final_value,
            "episode_return": episode_return,
            "episode_max_drawdown": episode_max_drawdown,
            "episode_sharpe": episode_sharpe,
            "num_steps": int(len(g)),
            "num_trades": int(executed_mask_g.sum()),
            "avg_trade_fraction": avg_trade_fraction_g,
            "total_fees_paid": float(g["fees_paid"].sum()),
        })

    per_market_df = pd.DataFrame(per_market_metrics)

    total_initial_value = float(per_market_df["initial_value"].sum())
    total_final_value = float(per_market_df["final_value"].sum())
    cumulative_return = total_final_value / max(total_initial_value, 1e-8) - 1.0

    pooled_step_returns = trades["step_portfolio_return"].to_numpy(dtype=float)
    pooled_step_returns = pooled_step_returns[np.isfinite(pooled_step_returns)]

    if len(pooled_step_returns) > 1 and np.std(pooled_step_returns, ddof=1) > 1e-12:
        annualized_sharpe = float(
            np.sqrt(periods_per_year) * np.mean(pooled_step_returns) / np.std(pooled_step_returns, ddof=1)
        )
    else:
        annualized_sharpe = np.nan

    executed_mask = trades["trade_notional"] > 0
    avg_trade_fraction = float(
        (
            trades.loc[executed_mask, "trade_notional"]
            / trades.loc[executed_mask, "portfolio_value"].clip(lower=1e-8)
        ).mean()
    ) if executed_mask.any() else 0.0

    metrics = {
        "cumulative_return": float(cumulative_return),
        "annualized_sharpe": annualized_sharpe,
        "max_drawdown": float(per_market_df["episode_max_drawdown"].min()),
        "avg_trade_fraction": avg_trade_fraction,
        "num_trades": int(executed_mask.sum()),
        "num_steps": int(len(trades)),
        "num_markets": int(trades["market_id"].nunique()),
        "final_portfolio_value": float(total_final_value),
    }

    return per_market_df, metrics


def evaluate_action_selector(
    action_selector,
    markets_dict: Dict[str, pd.DataFrame],
    rl_config: Dict[str, Any],
) -> Tuple[pd.DataFrame, pd.DataFrame, Dict[str, float]]:
    env = make_eval_env(markets_dict)
    records: List[Dict[str, Any]] = []

    for _ in range(len(env.market_ids)):
        obs, info = env.reset()
        done = False
        step_idx = 0

        while not done:
            action = action_selector(obs, info, env, step_idx)
            next_obs, reward, terminated, truncated, step_info = env.step(action)
            done = terminated or truncated

            records.append({
                "market_id": step_info["market_id"],
                "timestamp": step_info["timestamp"],
                "yes_price": step_info["price"],
                "no_price": step_info["no_price"],
                "next_ret": step_info["next_ret"],
                "action_type": step_info["action_type"],
                "size_bin": step_info["size_bin"],
                "size_fraction": step_info["size_fraction"],
                "cash": step_info["cash"],
                "yes_qty": step_info["yes_qty"],
                "no_qty": step_info["no_qty"],
                "trade_notional": step_info["trade_notional"],
                "fees_paid": step_info["fees_paid"],
                "executed_qty": step_info["executed_qty"],
                "forced_liquidation_notional": step_info["forced_liquidation_notional"],
                "reward": reward,
                "risk_penalty": step_info["risk_penalty"],
                "trade_penalty": step_info["trade_penalty"],
                "portfolio_value": step_info["portfolio_value"],
            })

            obs = next_obs
            info = step_info
            step_idx += 1

    trades = pd.DataFrame(records)
    per_market_df, metrics = compute_metrics_from_trades(trades)
    return trades, per_market_df, metrics


def evaluate_agent(
    model: PPO,
    markets_dict: Dict[str, pd.DataFrame],
    rl_config: Dict[str, Any],
) -> Tuple[pd.DataFrame, pd.DataFrame, Dict[str, float]]:
    def model_selector(obs, info, env, step_idx):
        action, _ = model.predict(obs, deterministic=True)
        return action

    return evaluate_action_selector(model_selector, markets_dict, rl_config)


max_size_bin = RL_CONFIG["action_bins"] - 1

def hold_cash_selector(obs, info, env, step_idx):
    return np.array([0, 0], dtype=np.int64)

def buy_yes_and_hold_selector(obs, info, env, step_idx):
    if step_idx == 0:
        return np.array([1, max_size_bin], dtype=np.int64)
    return np.array([0, 0], dtype=np.int64)

def buy_no_and_hold_selector(obs, info, env, step_idx):
    if step_idx == 0:
        return np.array([2, max_size_bin], dtype=np.int64)
    return np.array([0, 0], dtype=np.int64)

def momentum_selector(obs, info, env, step_idx):
    if env.yes_qty <= 0.0 and env.no_qty <= 0.0:
        if step_idx == 0:
            return np.array([0, 0], dtype=np.int64)

        recent_ret = float(obs[RL_CONFIG["lookback"] + 3])
        if recent_ret > 0:
            return np.array([1, max_size_bin], dtype=np.int64)
        if recent_ret < 0:
            return np.array([2, max_size_bin], dtype=np.int64)
        return np.array([0, 0], dtype=np.int64)

    return np.array([0, 0], dtype=np.int64)


valid_trades, valid_per_market, valid_metrics = evaluate_agent(best_model, valid_markets, RL_CONFIG)
test_trades, test_per_market, test_metrics = evaluate_agent(best_model, test_markets, RL_CONFIG)

baseline_selectors = {
    "hold_cash": hold_cash_selector,
    "buy_yes_and_hold": buy_yes_and_hold_selector,
    "buy_no_and_hold": buy_no_and_hold_selector,
    "momentum": momentum_selector,
}

baseline_results: List[Dict[str, Any]] = []

for split_name, split_markets in [("valid", valid_markets), ("test", test_markets)]:
    for baseline_name, selector in baseline_selectors.items():
        _, _, baseline_metrics = evaluate_action_selector(selector, split_markets, RL_CONFIG)
        row = {"split": split_name, "strategy": baseline_name}
        row.update(baseline_metrics)
        baseline_results.append(row)

comparison_rows = [
    {"split": "valid", "strategy": "ppo_rl", **valid_metrics},
    {"split": "test", "strategy": "ppo_rl", **test_metrics},
]
comparison_rows.extend(baseline_results)
comparison_df = pd.DataFrame(comparison_rows)

valid_trades.to_csv(os.path.join(CONFIG["outdir"], "valid_rl_trades.csv"), index=False)
test_trades.to_csv(os.path.join(CONFIG["outdir"], "test_rl_trades.csv"), index=False)
valid_per_market.to_csv(os.path.join(CONFIG["outdir"], "valid_rl_per_market_metrics.csv"), index=False)
test_per_market.to_csv(os.path.join(CONFIG["outdir"], "test_rl_per_market_metrics.csv"), index=False)
comparison_df.to_csv(os.path.join(CONFIG["outdir"], "strategy_comparison.csv"), index=False)

with open(os.path.join(CONFIG["outdir"], "valid_rl_metrics.json"), "w", encoding="utf-8") as f:
    json.dump(valid_metrics, f, indent=2)
with open(os.path.join(CONFIG["outdir"], "test_rl_metrics.json"), "w", encoding="utf-8") as f:
    json.dump(test_metrics, f, indent=2)

print("Validation metrics")
display(valid_metrics)
print("Test metrics")
display(test_metrics)
print("Strategy comparison")
display(comparison_df.sort_values(["split", "strategy"]).reset_index(drop=True))

Validation metrics

{'cumulative_return': 0.18951695843684102,
 'annualized_sharpe': 0.8016882394922945,
 'max_drawdown': -0.6736154942335155,
 'avg_trade_fraction': 0.5828364604984102,
 'num_trades': 456,
 'num_steps': 36070,
 'num_markets': 461,
 'final_portfolio_value': 549825.9667301567}

Test metrics

{'cumulative_return': 0.1630767670885136,
 'annualized_sharpe': 1.2084001296148668,
 'max_drawdown': -0.74170828125,
 'avg_trade_fraction': 0.5988892152337931,
 'num_trades': 879,
 'num_steps': 36327,
 'num_markets': 471,
 'final_portfolio_value': 550226.7166567282}

Strategy comparison

,split,strategy,cumulative_return,annualized_sharpe,max_drawdown,avg_trade_fraction,num_trades,num_steps,num_markets,final_portfolio_value
0,test,buy_no_and_hold,0.008242,0.998076,-0.998919,1.007852,471,36327,471,472371.375737
1,test,buy_yes_and_hold,-0.039135,2.145606,-0.999408,1.009674,471,36327,471,456764.887731
2,test,hold_cash,0.000000,NaN,0.000000,0.000000,0,36327,471,471000.000000
3,test,momentum,-0.039656,1.510100,-0.999408,1.823372,445,36327,471,452322.126423
4,test,ppo_rl,0.163077,1.208400,-0.741708,0.598889,879,36327,471,550226.716657
5,valid,buy_no_and_hold,-0.005286,0.810277,-0.959070,1.003343,461,36070,461,461299.353583
6,valid,buy_yes_and_hold,0.069148,2.126553,-0.988649,1.006205,461,36070,461,501630.840455
7,valid,hold_cash,0.000000,NaN,0.000000,0.000000,0,36070,461,461000.000000
8,valid,momentum,-0.015168,1.261725,-0.988677,1.054969,435,36070,461,454007.757073
9,valid,ppo_rl,0.189517,0.801688,-0.673615,0.582836,456,36070,461,549825.966730